-- auto-generated definition
create table book
(
    id        int auto_increment,
    name      varchar(255) charset utf8 null,
    author    varchar(255) charset utf8 null,
    year      date                      null,
    publisher varchar(255) charset utf8 null,
    price     double                    null,
    available int default 9999          null,
    constraint book_id_uindex
        unique (id)
);

alter table book
    add primary key (id);

insert into book (name, author, year, publisher, price) VALUES ('马尔克斯：百年孤独（50周年纪念版）', '加西亚·马尔克斯 著，新经典 出品', '2017-08-01', '南海出版公司', '55.00');
insert into book (name, author, year, publisher, price) VALUES ('蛤蟆先生去看心理医生（年销200万册！英国经典心理咨询入门书，知名心理学家李松蔚强烈推荐）', '罗伯特·戴博德，果麦文化 出品', '2020-07-01', '天津人民出版社', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('活着（精装版，余华代表作，易烊千玺推荐阅读版本）', '余华 著，新经典 出品', '2017-06-01', '北京十月文艺出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('你当像鸟飞往你的山（中文版销量超200万册，比尔·盖茨年度特别推荐！登顶《纽约时报》畅销榜80+周，这本书比你听说的还要好！）', '塔拉 · 韦斯特弗  著 ， 新经典  出品', '2019-11-01', '南海出版公司', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('苏菲的世界（平装新版）五六年级阅读乔斯坦贾德哲学入门书作家出版社', '乔斯坦·贾德', '2017-09-19', '作家出版社', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('平凡的世界：全三册（全新2021版，茅盾文学奖获奖作品，激励青年的不朽经典）', '路遥  著 ， 新经典  出品', '2021-06-01', '北京十月文艺出版社', '138.00');
insert into book (name, author, year, publisher, price) VALUES ('窗边的小豆豆(2018版)', '（日）黑柳彻子， 爱心树童书  出品', '2018-05-01', '南海出版公司', '39.50');
insert into book (name, author, year, publisher, price) VALUES ('美的历程（李泽厚代表名作）', '李泽厚', '2014-03-01', '生活.读书.新知三联书店', '56.00');
insert into book (name, author, year, publisher, price) VALUES ('云边有个小卖部（陆定昊诚挚推荐，随书附赠云边镇四季明信片和张嘉佳作词单曲彩蛋）', '张嘉佳 著,博集天卷 出品', '2018-07-01', '湖南文艺出版社', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('古代人的日常生活（古代的光棍多吗？古人怎么擦屁屁？古人夏天如何驱蚊？满足你对古人日常生活的全部好奇！）（当当典藏版）', '讲历史的王老师 著；读客文化 出品', '2020-02-10', '江苏凤凰文艺出版社', '69.90');
insert into book (name, author, year, publisher, price) VALUES ('少年读史记（套装全5册）', '张嘉骅', '2015-09-01', '青岛出版社', '100.00');
insert into book (name, author, year, publisher, price) VALUES ('三体：全三册 刘慈欣代表作，亚洲“雨果奖”获奖作品！', '刘慈欣', '2010-11-01', '重庆出版社', '93.00');
insert into book (name, author, year, publisher, price) VALUES ('被讨厌的勇气：“自我启发之父”阿德勒的哲学课 岸见一郎', '岸見一郎, 古賀史健', '2020-03-05', '机械工业出版社', '55.00');
insert into book (name, author, year, publisher, price) VALUES ('神奇校车·桥梁书版（全20册）', '乔安娜柯尔　著 布鲁斯迪根 图　施芳　译', '2014-04-01', '贵州人民出版社', '150.00');
insert into book (name, author, year, publisher, price) VALUES ('东野圭吾：白夜行（易烊千玺、孟非推荐，东野圭吾作品无冕之王）', '[日]东野圭吾 著，新经典 出品', '2017-08-09', '南海出版公司', '59.60');
insert into book (name, author, year, publisher, price) VALUES ('杀死一只知更鸟（豆瓣9.2，关于勇气与正义的成长教科书，影响全球5000万家庭的“教养宝典”，奥巴马、贝克汉姆、奥普拉鼎力推荐）', '哈珀·李　著  李育超 译', '2017-02-01', '译林出版社', '48.00');
insert into book (name, author, year, publisher, price) VALUES ('古代人的日常生活2（典藏版）（古代房价高吗？古人如何抗疫？古人如何学外语？一本书满足你对古人日常生活的全部好奇！）', '讲历史的王老师；读客文化 出品', '2021-08-01', '江苏凤凰文艺出版社', '75.90');
insert into book (name, author, year, publisher, price) VALUES ('东野圭吾：恶意（2016版，东野圭吾四大杰作之一）', '东野圭吾 著，娄美莲 译，新经典 出品', '2016-11-01', '南海出版公司', '39.50');
insert into book (name, author, year, publisher, price) VALUES ('人生海海（麦家重磅力作，莫言、董卿盛赞，连续两年高居畅销榜，发行量超200万册）', '麦家  著 ，新经典  出品', '2019-04-16', '北京十月文艺出版社', '55.00');
insert into book (name, author, year, publisher, price) VALUES ('皮特猫·3~6岁好性格养成书：第一辑（共6册）（乐观、积极、开朗……荣获19项大奖的好性格榜样，在美国家喻户晓）', '(美)艾瑞克·利温等 著；彭懿等译；读客文化 出品', '2018-07-01', '文汇出版社', '139.90');
insert into book (name, author, year, publisher, price) VALUES ('霍乱时期的爱情（《百年孤独》作者马尔克斯传世巨著，展示爱情的所有可能）', '（哥伦比亚）加西亚 · 马尔克斯  著 ， 新经典  出品', '2020-03-01', '南海出版公司', '69.00');
insert into book (name, author, year, publisher, price) VALUES ('米小圈脑筋急转弯（第一辑）（套装共4册）', '北猫', '2016-01-01', '四川少儿出版社', '64.00');
insert into book (name, author, year, publisher, price) VALUES ('神奇校车·图画书版（全12册，新增科学博览会1册）', '(美)乔安娜柯尔 著 ,(美)布鲁斯·迪根 图', '2018-05-10', '贵州人民出版社', '198.00');
insert into book (name, author, year, publisher, price) VALUES ('我们的身体', '[法]艾德兰  文，[法]巴尔博里尼  绘，荣信教育  出品', '2012-06-01', '未来出版社', '155.00');
insert into book (name, author, year, publisher, price) VALUES ('面纱（毛姆关于女性精神觉醒的经典作品，三次改编成电影。2018全新编校+无删减全译本）', '〔英〕毛姆 著，王晋华 译', '2019-01-01', '时代文艺出版社', '27.00');
insert into book (name, author, year, publisher, price) VALUES ('遥远的救世主（热播电视剧天道原著，即小说《背叛》，畅销遥远的救世主作者豆豆三部曲之一）', '豆豆', '2018-10-09', '作家出版社', '48.00');
insert into book (name, author, year, publisher, price) VALUES ('孩子读得懂的山海经（共3册）神话+神兽+异人国', '兰梦醒 ，贺维芳 ，许萍萍 著，青鸟童书 出品', '2020-11-04', '北京理工大学出版社', '219.00');
insert into book (name, author, year, publisher, price) VALUES ('非暴力沟通', '（美）马歇尔?卢森堡著   阮胤华译', '2018-08-31', '华夏出版社', '49.00');
insert into book (name, author, year, publisher, price) VALUES ('财务自由之路（全三册）当当专享版 赠送精美书签', '（德）博多·舍费尔', '2019-02-20', '现代出版社', '135.00');
insert into book (name, author, year, publisher, price) VALUES ('小金鱼逃走了', '五味太郎 著， 爱心树童书  出品', '2017-04-01', '新星出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('半小时漫画中国史1-5（全5册）（中国史大结局！笑着笑着，大清就亡了！漫画科普开创者混子哥陈磊新作！）', '陈磊 著;读客文化 出品', '2020-12-31', '海南出版社', '219.50');
insert into book (name, author, year, publisher, price) VALUES ('DK博物大百科——自然界的视觉盛宴', '英国DK公司', '2018-09-01', '科学普及出版社', '458.00');
insert into book (name, author, year, publisher, price) VALUES ('消失的13级台阶（罗翔推荐！荣获日本推理小说至高荣誉江户川乱步奖！是否值得为一场痛快的复仇，陪葬掉自己的人生？）', '(日)高野和明 著；读客文化 出品', '2020-04-29', '上海文艺出版社', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('三毛全集02：撒哈拉的故事', '三毛 著，新经典 出品', '2017-04-01', '北京十月文艺出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('文城（余华新书，时隔8年重磅归来，《活着》之后又一精彩力作）', '余华  著 ， 新经典  出品', '2021-03-03', '北京十月文艺出版社', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('宫西达也“你肯定能行”绘本（全18册）', '[日]宫西达也', '2020-10-01', '青岛出版社', '318.00');
insert into book (name, author, year, publisher, price) VALUES ('乌合之众 : 大众心理研究（群体心理学创始人古斯塔夫·勒庞代表作之一。极简翻译文风，语言深入浅出，减少艰深晦涩）', '(法) 古斯塔夫·勒庞 著，马晓佳 译', '2018-04-06', '民主与建设出版社', '26.00');
insert into book (name, author, year, publisher, price) VALUES ('致我独一无二的宝贝（联合国秘书长安东尼奥·古特雷斯高度评价，母婴育儿大V小土大橙子翻译，荣获独立图书*奖）', '（美）沙尼·金 著，（瑞士）安娜·霍瓦特 绘，小土大橙子 译', '2020-10-14', '湖南美术出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('小狗钱钱（附赠免费亲子财商课+理财秘籍思维导图）', '博多·舍费尔', '2021-01-20', '中信出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('走遍中国 图说天下 寻梦之旅', '霍晨昕', '2019-02-01', '四川人民出版社', '29.90');
insert into book (name, author, year, publisher, price) VALUES ('【樊登推荐】考试脑科学 脑科学中的高效记忆法（图灵出品）', '[日]池谷裕二', '2021-03-01', '人民邮电出版社', '59.80');
insert into book (name, author, year, publisher, price) VALUES ('次第花开 修订版', '希阿荣博堪布', '2017-02-01', '海南出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('我爸爸+我妈妈（全2册）——清华附小推荐经典儿童绘本 ！（启发童书馆出品）', '〔英〕安东尼?布朗', '2019-10-01', '河北教育出版社', '79.60');
insert into book (name, author, year, publisher, price) VALUES ('小王子（原版精美插图，傅雷翻译出版奖得主郑克鲁法文直译。揭秘作者传奇人生，展示与《小王子》有关的钱币、纪念章、邮票等）', '(法) 圣埃克苏佩里、郑克鲁译', '2018-07-19', '浙江工商大学出版社', '26.00');
insert into book (name, author, year, publisher, price) VALUES ('作家榜经典：月亮与六便士（全新未删节插图珍藏版！毛姆写给年轻人的梦想之书！满地都是六便士，他却抬头看见了月亮！）', '[英] 毛姆 著，作家榜经典 出品，徐淳刚（诗人） 译，大星文化，高更 绘', '2017-01-10', '浙江文艺出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('米小圈上学记一年级（套装共4册）', '北猫', '2018-04-01', '四川少儿出版社', '100.00');
insert into book (name, author, year, publisher, price) VALUES ('如果历史是一群喵1-8（套装共8册）', '肥志编绘，漫友文化出品', '2021-05-28', '广东旅游出版社', '458.00');
insert into book (name, author, year, publisher, price) VALUES ('信谊世界精选图画书-猜猜我有多爱你', '[英] 山姆·麦克布雷尼 著，[英] 安妮塔·婕朗 绘，梅子涵 译', '2020-09-01', '明天出版社', '43.80');
insert into book (name, author, year, publisher, price) VALUES ('在峡江的转弯处：陈行甲人生笔记', '陈行甲', '2021-01-26', '人民日报出版社', '48.00');
insert into book (name, author, year, publisher, price) VALUES ('世界尽头的咖啡馆（做决定前读一遍，少走弯路！美国57所高校指定研讨读物）', '约翰·史崔勒基， 译者 万洁，果麦文化 出品', '2019-05-01', '天津人民出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('米小圈漫画成语（套装共5册）', '北猫', '2020-01-01', '四川少儿出版社', '100.00');
insert into book (name, author, year, publisher, price) VALUES ('人间失格（日本小说家太宰治代表作，一个对村上春树影响至深的绝望凄美故事）', '（日）太宰治　著，杨伟　译', '2015-08-01', '作家出版社', '25.00');
insert into book (name, author, year, publisher, price) VALUES ('东野圭吾：嫌疑人X的献身（易烊千玺、王凯推荐，至为纯粹的爱情，绝好的诡计）', '东野圭吾 著，刘子倩 译，新经典 出品', '2014-06-01', '南海出版公司', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('东野圭吾：解忧杂货店（胡歌、王俊凯、刘昊然倾情推荐，简体中文1000万册纪念版）', '（日）东野圭吾  著， 新经典  出品', '2020-09-01', '南海出版公司', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('亲密关系：通往灵魂的桥梁（新版）：杨天真推荐，这本书告诉我们如何穿透自我障碍，用爱酿造幸福秘方', '（加）克里斯多福·孟 著,博集天卷 出品', '2019-04-01', '湖南文艺出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('东野圭吾：无名之町（2021年高能新作！神尾大侦探首秀！）', '（日）东野圭吾  著 ，新经典  出品', '2021-06-01', '南海出版公司', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('李诞脱口秀工作手册（李诞分享创作经验！创意是智力活儿，也是体力活儿，归根结底是苦力活儿！）', '李诞；读客文化 出品', '2021-08-01', '江苏凤凰文艺出版社', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('苏东坡传（林语堂纪念典藏精装版）', '林语堂 著,博集天卷 出品', '2018-01-01', '湖南文艺出版社', '52.00');
insert into book (name, author, year, publisher, price) VALUES ('四五快读 全彩图升级版——幼儿快速识字阅读法（全8册）(让孩子爱上阅读 快乐识字)[精选套装]', '杨其铎　著', '2012-02-01', '湖南科技出版社', '211.40');
insert into book (name, author, year, publisher, price) VALUES ('给男孩的情绪管理绘本（套装全5册）', '乐凡 段张取艺', '2021-03-01', '青岛出版社', '90.00');
insert into book (name, author, year, publisher, price) VALUES ('半小时漫画青春期：生理篇（从变声长痘到脸红心跳，笑着笑着解决青春期困扰！爆笑全解生理知识）', '陈磊·半小时漫画团队 著；读客文化 出品', '2021-07-30', '天津科学技术出版社', '49.00');
insert into book (name, author, year, publisher, price) VALUES ('这就是物理（函套10册）', '约瑟夫·米森（Joseph Midthun） 萨缪·希提（Sam Hiti）', '2019-07-01', '北京理工大学出版社', '200.00');
insert into book (name, author, year, publisher, price) VALUES ('小鸡球球触感玩具书：全5册', '[日]入山智 著绘；崔维燕 译；心喜阅童书出品', '2016-11-15', '长江少年儿童出版社', '250.00');
insert into book (name, author, year, publisher, price) VALUES ('房思琪的初恋乐园 （豆瓣9.2高分！数百万读者强烈共鸣的文学绝唱）', '林奕含 著，磨铁图书 出品', '2018-02-01', '北京联合出版有限公司', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('月光落在左手上（精装珍藏版）', '余秀华  著 ， 新经典  出品', '2020-09-01', '北京十月文艺出版社', '58.00');
insert into book (name, author, year, publisher, price) VALUES ('吹牛大王历险记（德国原版精美插图本，充满欢乐的百年童话，未删节全译，详细注释本）', '〔德〕埃·拉斯伯〔德〕戈·毕尔格著， 邵灵侠译', '2017-12-01', '浙江工商大学出版社', '19.00');
insert into book (name, author, year, publisher, price) VALUES ('天堂旅行团（当当专享寄语印签环衬+精编小册子，继《全世界》《云边》之后，张嘉佳新书2021全新长篇力作）', '张嘉佳 著,博集天卷 出品', '2021-08-01', '湖南文艺出版社', '48.00');
insert into book (name, author, year, publisher, price) VALUES ('黄金时代（2021版，王小波成名代表作，当代文学经典！罗翔、肖战、朱一龙、麦家、李诞都在读王小波。)', '王小波  著 ，新经典  出品', '2021-06-01', '北京十月文艺出版社', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('拼音真好玩（全彩6册）（从幼小衔接到一年级，拼音学习启蒙书，附赠超实用拼音全表） 小猛犸童书出品', '周霞 著 段张取艺 绘', '2018-10-15', '电子工业出版社', '99.00');
insert into book (name, author, year, publisher, price) VALUES ('沟通的方法（别怕，沟通是场无限游戏。得到CEO脱不花为你备好的沟通心法，助你在职场上一路开挂）团购电话:4001066666转6', '脱不花 著，得到图书 出品', '2021-06-11', '新星出版社', '69.00');
insert into book (name, author, year, publisher, price) VALUES ('米小圈脑筋急转弯（第二辑）(套装共4册）', '北猫', '2020-06-01', '四川少儿出版社', '64.00');
insert into book (name, author, year, publisher, price) VALUES ('大熊先生盖房子（澳大利亚青少年图书奖获奖作家、加拿大总督奖获奖绘者联袂打造）', '(澳) 珍·戈德温、(澳) 迈克尔·瓦格纳 文，(加) 安德鲁·乔伊纳 图，方素珍 译，小当当童书馆 出品', '2017-11-01', '中译出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('少年读徐霞客游记（游中国·地理启蒙，全3册）', '刘兴诗', '2020-09-01', '青岛出版社', '100.00');
insert into book (name, author, year, publisher, price) VALUES ('屁屁侦探思维进阶版 第一辑（精装4册）', '(日) Troll 文/图，彭懿 译', '2021-03-01', '二十一世纪出版社', '140.00');
insert into book (name, author, year, publisher, price) VALUES ('写给儿童的中国历史（中国孩子的历史启蒙，真正写给孩子看的中国通史，全彩铜版14册）', '陈卫平著 步印童书 出品', '2014-04-01', '新世界出版社', '355.00');
insert into book (name, author, year, publisher, price) VALUES ('正面管教(修订版)', '[美] 简·尼尔森', '2016-07-01', '北京联合出版公司', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('学会管自己幼儿版-歪歪兔自控力教育系列绘本（全10册，幼儿园情绪管理与时间管理绘本）', '歪歪兔关键期早教项目组著绘', '2017-06-01', '海豚出版社', '88.00');
insert into book (name, author, year, publisher, price) VALUES ('沉思录', '马可.奥勒留 青豆书坊 出品', '2008-02-01', '中央编译出版社', '20.00');
insert into book (name, author, year, publisher, price) VALUES ('心理抚养', '李玫瑾', '2021-06-01', '上海三联书店', '46.80');
insert into book (name, author, year, publisher, price) VALUES ('美的历程（李泽厚毕生扛鼎之作 中国美学史绕不开的经典）', '李泽厚', '2021-02-01', '人民文学出版社', '55.00');
insert into book (name, author, year, publisher, price) VALUES ('夏洛的网(2020版）（三年级阅读经典书目）', '（美）怀特　著，任溶溶　译', '2014-08-01', '上海译文出版社', '37.00');
insert into book (name, author, year, publisher, price) VALUES ('愿你慢慢长大（与刘瑜、周国平、冯唐等名家一起开始一场温柔的教养旅程，聊一聊关于教养的真心话，感受孩子成长的真实意义。）', '刘瑜、周国平等，联合读创   出品', '2018-01-01', '北京联合出版有限公司', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('100层的房子系列（全4册，《100层的房子》+《地下100层的房子》+《海底100层的房子》+《天空100层的房子》）', '[日]岩井俊雄', '2018-08-01', '北京科学技术出版社', '156.00');
insert into book (name, author, year, publisher, price) VALUES ('毛泽东选集（全四册，32开）', '毛泽东 著', '1991-06-01', '人民出版社', '81.00');
insert into book (name, author, year, publisher, price) VALUES ('小小聪明豆绘本系列:波西和皮普(套装共7册)', '（德）阿克塞尔·舍夫勒著/绘', '2015-08-17', '外语教学与研究出版社', '73.00');
insert into book (name, author, year, publisher, price) VALUES ('第七天（2018版）', '余华', '2018-08-01', '新星出版社', '39.50');
insert into book (name, author, year, publisher, price) VALUES ('我的第一本地理启蒙书', '郑利强 段虹(绘) 步印童书 出品', '2016-06-01', '新世界出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('沙丘六部曲（同名电影全国上映！《降临》导演执导、“甜茶”“灭霸”、张震等主演。每个“不可不读”的书单上都有《沙丘》）', '(美) 弗兰克·赫伯特  著；读客文化 出品', '2019-09-30', '江苏文艺出版社', '394.90');
insert into book (name, author, year, publisher, price) VALUES ('彩虹色的花', '麦克?格雷涅茨', '2018-07-01', '二十一世纪出版社', '46.00');
insert into book (name, author, year, publisher, price) VALUES ('真希望我父母读过这本书', '菲莉帕·佩里（Philippa Perry）', '2020-08-10', '中信出版社', '48.00');
insert into book (name, author, year, publisher, price) VALUES ('心若菩提(增订本)', '曹德旺 著', '2020-10-01', '人民出版社', '79.00');
insert into book (name, author, year, publisher, price) VALUES ('沉默的大多数（爱智慧、爱自由、反对愚蠢，读王小波的“上头之选”！依据王小波手稿、生前定稿修订多年讹误，SHOU度以读者视角排定蕞佳阅读顺序。）', '王小波  著 ， 新经典  出品', '2021-01-01', '北京十月文艺出版社', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('山月记（如果你很迷茫！自我拉扯！一定要读《山月记》。日本文豪中岛敦笔下的中国物语，常年入选日本国语教材）【果麦经典】', '（日）中岛敦，译者 徐建雄，绘者 撒旦君，果麦文化 出品', '2019-02-01', '三秦出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('人间值得（90岁心理医生恒子奶奶写给生活的哲思小书。十点读书、《读者》2019年度“十大影响力好书”、人民日报力荐2020新年书单。）', '[日]中村恒子（恒子奶奶）著，紫图图书  出品', '2019-09-01', '北京日报出版社（原同心出版社）', '49.90');
insert into book (name, author, year, publisher, price) VALUES ('巴巴爸爸大家族（精选典藏礼盒,全72册）', '［法］德鲁斯·泰勒 ［法］安娜特·缇森 著', '2020-10-01', '接力出版社', '1039.40');
insert into book (name, author, year, publisher, price) VALUES ('不一样的卡梅拉手绘本（1-12册）', '（法）克利斯提昂 约里波瓦著郑迪蔚译 ,（法）克利斯提昂 艾利施绘', '2013-06-01', '２１世纪出版社', '120.00');
insert into book (name, author, year, publisher, price) VALUES ('山茶文具店（陆定昊诚挚推荐，日本畅销作家小川糸备受好评暖心之作）', '小川糸 著,博集天卷 出品', '2018-03-31', '湖南文艺出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('夜晚的潜水艇(第四届宝珀理想国文学奖得主陈春成短篇小说集，游荡于旧山河与未知宇宙间，汉语的一种风度与可能性)', '陈春成 著，    理想国 出品', '2020-09-01', '上海三联书店', '52.00');
insert into book (name, author, year, publisher, price) VALUES ('橘子不是唯一的水果', '（英）珍妮特·温特森  著， 新经典  出品', '2018-04-01', '北京联合出版有限公司', '49.00');
insert into book (name, author, year, publisher, price) VALUES ('世界上最棒的礼物——图画中隐藏无数细节，让小小孩玩过瘾！', '文/图：赖马', '2019-06-30', '北京联合出版有限公司', '45.80');
insert into book (name, author, year, publisher, price) VALUES ('围城', '钱钟书　著', '1991-02-01', '人民文学出版社', '39.00');
insert into book (name, author, year, publisher, price) VALUES ('父母的语言：3000万词汇塑造更强大的学习型大脑', '[美]达娜·萨斯金德（Dana Suskind），MD 贝丝·萨斯金德（Bet', '2021-06-15', '机械工业出版社', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('如何说孩子才会听 怎么听孩子才肯说（全新修订版，涂磊推荐）', '（美）玛兹丽施　著，安燕玲　译 青豆书坊 出品', '2016-09-01', '中央编译出版社', '36.80');
insert into book (name, author, year, publisher, price) VALUES ('小熊和最好的爸爸（全7册）', '（荷）阿兰德·丹姆  著，（荷）亚历克斯·沃尔夫  绘，漆仰平，爱桐  译', '2007-11-01', '贵州人民出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('银火箭少年科幻系列·第1辑（8册。“雨果奖”得主、三体作者刘慈欣主编，套装内作者作品曾获银河奖特等奖等多项国际大奖）', '刘慈欣、[英]赫伯特·乔治·威尔斯、[英]玛丽·雪莱等 著，小当当童书馆 出品', '2018-04-02', '浙江教育出版社', '256.00');
insert into book (name, author, year, publisher, price) VALUES ('人间滋味（百岁奶奶喻泽琴遍尝人间滋味的生活哲学。人生哪，就是吃好点儿，看淡点儿。当当专享：奶奶金句主题藏书票。）', '蔡昀恩 著，白马时光出品', '2021-07-01', '江苏凤凰文艺出版社', '55.00');
insert into book (name, author, year, publisher, price) VALUES ('见识城邦·人类简史：从动物到上帝（新版）', '[以色列] 尤瓦尔·赫拉利（Yuval Noah Harari）', '2017-01-01', '中信出版社', '68.00');
insert into book (name, author, year, publisher, price) VALUES ('万物由来科学绘本 写给孩子的科普绘本', '项华', '2020-08-01', '北京联合出版有限公司', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('钱穆谈中国历史文化：中国历史精神', '钱穆', '2019-06-06', '贵州人民出版社', '26.00');
insert into book (name, author, year, publisher, price) VALUES ('富爸爸穷爸爸（新版本）当当投资理财类图书！本版随书附赠价值198元的“小白财商在线课程”', '【美】罗伯特·清崎    萧明 译', '2019-08-01', '四川人民出版社', '89.00');
insert into book (name, author, year, publisher, price) VALUES ('心安即是归处（季羡林百年生命智慧。央视《朗读者》多次动情朗读本书名篇，贾平凹、白岩松、金庸、林青霞诚意推荐）', '季羡林 著，文通天下 出品', '2020-08-01', '古吴轩出版社', '49.00');
insert into book (name, author, year, publisher, price) VALUES ('0-4岁幼儿认知小百科（全3册)', '[日]吉田纯子 绘；徐超 译；心喜阅童书 出品', '2014-02-01', '长江少年儿童出版社', '119.40');
insert into book (name, author, year, publisher, price) VALUES ('小熊宝宝绘本（简装全15册）蒲蒲兰经典绘本！新手妈妈的育儿宝典！(0-3岁)', '佐佐木洋子 文/图，蒲蒲兰 译', '2007-05-16', '新世纪出版社', '96.00');
insert into book (name, author, year, publisher, price) VALUES ('追风筝的人（李雪琴、高圆圆动情推荐，《纽约时报》畅销书榜上榜超100周）', '[美]卡勒德·胡赛尼（Khaled Hosseini） 著，李继宏 译', '2006-05-01', '上海人民出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('这世界很烦，但你要很可爱（只要你可爱，这个世界也会变得可爱）', '杨红 著', '2020-12-31', '水利水电出版社', '46.00');
insert into book (name, author, year, publisher, price) VALUES ('尼尔斯骑鹅旅行记（又译《尼尔斯骑鹅历险记》《骑鹅旅行记》，翻译家石琴娥译本）', '（瑞典）塞尔玛·拉格洛夫， 石琴娥译，小当当童书馆 出品', '2018-12-01', '安徽教育出版社', '24.80');
insert into book (name, author, year, publisher, price) VALUES ('童年（小学语文“快乐读书吧”·六年级上阅读，高尔基自传体三部曲之一，北师大教授郑海凌翻译）', '〔苏〕高尔基 著  郑海凌 译', '2017-08-01', '浙江工商大学出版社', '25.00');
insert into book (name, author, year, publisher, price) VALUES ('张爱玲全集01：倾城之恋（23岁张爱玲成名代表作！收录《倾城之恋》《第一炉香》《金锁记》等热门影视原著小说。王安忆、苏童、蔡康永推荐！）', '张爱玲 著  ，新经典  出品', '2019-01-01', '北京十月文艺出版社', '49.50');
insert into book (name, author, year, publisher, price) VALUES ('汉声中国童话（全12册）（精美礼盒装，享誉世界的经典童话  代代相传的文化瑰宝）', '汉声杂志社', '2018-01-30', '天地出版社', '936.00');
insert into book (name, author, year, publisher, price) VALUES ('李佳琦直播推荐 学会爱自己（防性侵，安全意识、行为习惯培养绘本，全14册）', '珊蒂克雷文，茱蒂柏斯玛，佩特拉敏特尔（德），安德烈乌斯塔科夫（德）等', '2016-02-01', '青岛出版社', '192.00');
insert into book (name, author, year, publisher, price) VALUES ('小王子（纪念版，李继宏口碑译作，作者基金会官方认证简体中文版）【果麦经典】', '（法）安托万·德·圣埃克苏佩里，译者 李继宏，果麦文化 出品', '2018-06-03', '天津人民出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('走遍世界 图说天下 寻梦之旅', '王秀莉', '2020-12-01', '四川人民出版社', '29.90');
insert into book (name, author, year, publisher, price) VALUES ('我的神奇马桶（奇思妙趣三部曲）（全3册）', '[日] 铃木典丈/著   彭懿/译', '2019-04-01', '贵州人民出版社', '89.40');
insert into book (name, author, year, publisher, price) VALUES ('心灵教科书绘本系列：西兰花先生的理发店（教会孩子：敢于打破常规思维，培养创新意识）丁虹绘本馆出品[3-6岁]', '[日] 福田纯子/著绘 丁虹/译', '2021-01-01', '海豚出版社', '59.80');
insert into book (name, author, year, publisher, price) VALUES ('拉鲁斯儿童心理小百科', '【法】卡琳·西蒙妮著，阳光博客 出品', '2021-08-01', '北京日报出版社（原同心出版社）', '88.00');
insert into book (name, author, year, publisher, price) VALUES ('小巴掌童话注音版8册百篇张秋生著 小学生课外读本', '张秋生', '2018-04-18', '山东科学技术出版社', '110.40');
insert into book (name, author, year, publisher, price) VALUES ('刘擎西方现代思想讲义（奇葩说导师、得到App主理人刘擎讲透西方思想史，马东、罗振宇、陈嘉映、施展力荐）', '刘擎 著; 得到图书 出品', '2021-01-17', '新星出版社', '79.00');
insert into book (name, author, year, publisher, price) VALUES ('原声触摸发声书：听，什么声音（套装全6册）', 'YOYO出版社 著绘,步步联盟 译', '2020-01-01', '开明出版社', '330.00');
insert into book (name, author, year, publisher, price) VALUES ('鸭子骑车记', '大卫·香农， 爱心树童书  出品', '2017-04-01', '新星出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('2021新版 点点点（小黄和小蓝升级版）宝宝视觉锻炼 杜莱大师作品 0-2 3-6岁幼儿启蒙绘本 早教书 [0-2岁]', '[法]埃尔维·杜莱', '2021-03-01', '海豚出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('信谊世界精选图画书-我的情绪小怪兽', '[西班牙] 安娜·耶纳斯 著', '2016-12-01', '明天出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('晚熟的人（莫言新书）', '莫言', '2020-07-01', '人民文学出版社', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('宫西达也超级绘本（加法超人与算术星人+狐狸爸爸笑了等全11册）', '[日]宫西达也', '2019-02-01', '青岛出版社', '186.00');
insert into book (name, author, year, publisher, price) VALUES ('钝感力（渡边淳一经典励志大作！央视新闻、《奇葩说》鼎力推荐，马东、蔡康永、杨天真、王俊凯推荐书目。写给易因小事敏感，什么都往心里去的人。)', '渡边淳一著；李迎跃 译;', '2018-01-01', '青岛出版社', '32.00');
insert into book (name, author, year, publisher, price) VALUES ('斯凯瑞金色童书·益智经典（百年诞辰纪念版，全4册）（原斯凯瑞金色童书·第一辑）', '【美】理查德·斯凯瑞  著 李晓平  等译', '2019-05-01', '贵州人民出版社', '98.00');
insert into book (name, author, year, publisher, price) VALUES ('也许你该找个人聊聊（继《蛤蟆先生去看心理医生》后，又一个关于心理咨询的动人故事；美国心理学泰斗欧文·亚隆推荐，李松蔚审校并作序）', '[美]洛莉·戈特利布，译者 张含笑 ，果麦文化 出品', '2021-06-01', '上海文化出版社', '68.00');
insert into book (name, author, year, publisher, price) VALUES ('断舍离（2019新版，全新修订50%以上内容）宫崎骏、张德芬、李冰冰的减法哲学', '山下英子 著,博集天卷 出品', '2019-01-11', '湖南文艺出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('宫西达也恐龙系列全套7册（你看起来好像很好吃+我是霸王龙等）', '宫西达也 文/图，杨文 晓晗 译', '2016-11-01', '２１世纪出版社', '126.00');
insert into book (name, author, year, publisher, price) VALUES ('把妈妈的话装进耳朵里', '(西) 玛尔塔·帕拉雷斯著 ; (西) 安 娜·格里马尔绘 ; 吴荷佳译', '2019-04-01', '北京科学技术出版社', '39.00');
insert into book (name, author, year, publisher, price) VALUES ('信谊世界精选图画书-逛商店街', '齐藤 忍 作绘，郭孚 译', '2020-07-01', '明天出版社', '56.80');
insert into book (name, author, year, publisher, price) VALUES ('在教室说错了没关系', '著 （日）莳田晋至，译 吴佳芬，绘 （日）长谷川知子', '2017-02-01', '青岛出版社', '36.00');
insert into book (name, author, year, publisher, price) VALUES ('爱的教育（语文教材“快乐读书吧”六年级上阅读，夏丏尊先生经典译本）', '（意）亚米契斯（Amicis E D） 著，夏丏尊　译', '2015-01-01', '安徽教育出版社', '20.00');
insert into book (name, author, year, publisher, price) VALUES ('小兔子学花钱系列·3~7岁孩子的财商启蒙绘本（全3册）（学花钱、学赚钱、学存钱，3岁对钱有概念，7岁会管零花钱！）', '(加)辛德斯·麦克劳德 著；读客文化 出品', '2020-03-13', '河南文艺出版社', '128.40');
insert into book (name, author, year, publisher, price) VALUES ('宫西达也“你如此可爱”绘本（第3辑 全7册）小小的我，大大的力量', '[日]宫西达也著；彭懿，米雅译', '2021-04-09', '青岛出版社', '132.00');
insert into book (name, author, year, publisher, price) VALUES ('大中华寻宝系列28 黑龙江寻宝记', '孙家裕', '2021-07-01', '二十一世纪出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('科幻世界·三体（典藏版）', '刘慈欣，科幻世界出品', '2016-06-30', '重庆出版社', '26.00');
insert into book (name, author, year, publisher, price) VALUES ('大语文那些事儿（全6册）大语文时代，得语文者得天下。字词、作文、阅读、古诗、古文一网打尽。', '赵旭', '2020-10-01', '北京理工大学出版社', '180.00');
insert into book (name, author, year, publisher, price) VALUES ('我有友情要出租（拼音版）', '方素珍 著 郝洛玟 绘', '2017-05-01', '新疆青少年出版社', '18.00');
insert into book (name, author, year, publisher, price) VALUES ('谈判：如何在博弈中获得更多(第四版)Everything is Negotiable', '(英) 盖温·肯尼迪 (Gavin Kennedy)', '2018-04-06', '民主与建设出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('手不是用来打人的（儿童好品德系列，全5册）孩子多读就见效的习惯养成书，缓解新手爸妈育儿焦虑，王志庚、孙莉莉、朱爱朝推荐', '（美）伊丽莎白·弗迪克、（美）玛丁妮·阿加西/著（美）玛丽卡·海因莱因/绘 陈薇薇、刘宣谷/译', '2018-04-01', '贵州教育出版社', '99.00');
insert into book (name, author, year, publisher, price) VALUES ('半小时漫画历史系列（共7册）中国史1-5+世界史1-2（看半小时漫画，通古今中外历史！混子哥新作！附赠定制版时间轴）', '陈磊.半小时漫画团队 著；读客文化 出品', '2021-06-30', '文汇出版社', '309.30');
insert into book (name, author, year, publisher, price) VALUES ('遇见未知的自己：全新修订版', '张德芬 著,博集天卷 出品', '2019-12-15', '湖南文艺出版社', '52.00');
insert into book (name, author, year, publisher, price) VALUES ('白鹿原（新版，央视《读书》推荐，含白鹿原+信任+蚕儿+霞光灿烂的早晨）', '陈忠实', '2019-03-28', '作家出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('bibi动物园：忍不住想打扰你（当当专享作者签章本，超人气原创治愈小漫画！随手一翻，嘴角一弯。2100万人点赞，阅读量超5亿！）', 'bibi 园长 著 ， 新经典   出品', '2021-09-01', '南海出版公司', '49.00');
insert into book (name, author, year, publisher, price) VALUES ('高效能人士的七个习惯（30周年纪念版）（全新增订版）（新增《纽约时报》畅销肖恩·柯维全新观点,管理大师吉姆·柯林斯作序）', '（美）史蒂芬·柯维 ，高新勇、王亦兵、葛雪蕾译； 中青文  出品', '2020-05-30', '中国青年出版社', '79.00');
insert into book (name, author, year, publisher, price) VALUES ('趣说中国史：如果把中国422位皇帝放在一个群里，他们会聊些什么？', '趣哥 著', '2020-11-01', '台海出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('米小圈上学记二年级（套装共4册）', '北猫', '2018-04-01', '四川少儿出版社', '100.00');
insert into book (name, author, year, publisher, price) VALUES ('外婆的道歉信（外婆说，要大笑要做梦要与众不同。人生是一场伟大的冒险。销量突破100万册。随书附赠一封神秘道歉信）', '[瑞典]弗雷德里克·巴克曼，译者 孟汇一，果麦文化 出品', '2017-05-01', '天津人民出版社', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('哈利·波特（套装1-7册）《语文》教材推荐阅读书目，外国儿童文学经典，新英国版封面平装版', '（英）J.K.罗琳 著； 苏农，马爱农，马爱新 译', '2018-11-01', '人民文学出版社', '438.00');
insert into book (name, author, year, publisher, price) VALUES ('天才在左 疯子在右(全新完整版)', '高铭 著，磨铁图书 出品', '2018-05-01', '北京联合出版有限公司', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('小英雄雨来 红色经典故事 快乐读书吧 六年级上册推荐阅读(中小学生课外阅读指导丛书)无障碍阅读 彩插励志版 5万多名读者热评！', '管桦', '2019-06-01', '南方出版社', '19.80');
insert into book (name, author, year, publisher, price) VALUES ('华夏万卷 楷书入门6件套 楷书字帖田英章书钢笔字帖成人学生硬笔书法教程初学者基础字帖(赠控笔训练)', '田英章 书', '2018-12-01', '上海交通大学出版社', '66.00');
insert into book (name, author, year, publisher, price) VALUES ('皮囊（400万册纪念版，直面人生的难题，刻在骨头里的故事，容纳一个个既失去家乡又未到达远方的生命）', '蔡崇达，果麦文化 出品', '2019-05-01', '天津人民出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('边城（沈从文代表作）', '沈从文', '2019-04-01', '中国友谊出版公司', '32.00');
insert into book (name, author, year, publisher, price) VALUES ('科幻世界·三体Ⅲ·死神永生（典藏版）', '刘慈欣，科幻世界出品', '2016-06-30', '重庆出版社', '48.00');
insert into book (name, author, year, publisher, price) VALUES ('活法', '【日】稻盛和夫', '2019-11-01', '东方出版社', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('小鸡球球成长绘本系列：全6册', '[日]入山智 著；崔维燕 译；心喜阅童书 出品', '2018-02-02', '长江少年儿童出版社', '142.80');
insert into book (name, author, year, publisher, price) VALUES ('封神演义(青少版，依据原著改写成现代白话文，适合小学高年级和初中生阅读)', '[明] 许仲琳著   富强 张燕均 改编', '2017-01-01', '浙江教育出版社', '28.00');
insert into book (name, author, year, publisher, price) VALUES ('花婆婆——清华附小推荐的经典绘本！美国国家图书奖作品！', '文/图：〔美〕芭芭拉库尼', '2019-11-11', '河北教育出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('夏天、烟火和我的尸体（张震、田燚推荐。乙一16岁惊世成名作，高口碑暗黑杰作，获第6届JUMP小说大奖）', '（日）乙一   著，  新经典   出品', '2019-09-01', '南海出版公司', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('一九八四（又译“1984”。奥威尔代表作，反乌托邦杰作之一）', '[英]乔治·奥威尔 著,傅霞 译', '2018-02-05', '时代文艺出版社', '32.00');
insert into book (name, author, year, publisher, price) VALUES ('这世界很好，但你也不差（打破满意度低幸福感差，这世界真叫人疲倦的死循环。万特特全新作品，《这世界很烦，但你要很可爱》姊妹篇）', '万特特', '2021-08-01', '新世界出版社', '49.00');
insert into book (name, author, year, publisher, price) VALUES ('数学帮帮忙（全25册+导读手册）超值礼盒装 （多功能数学绘本，清华附小公开课指定用书！小学数学学习）', '（美）达芙妮·斯金纳', '2019-12-01', '新蕾出版社', '275.00');
insert into book (name, author, year, publisher, price) VALUES ('丰子恺万般滋味，都是生活', '丰子恺', '2018-09-01', '华中科技大学出版社', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('大侦探福尔摩斯（第1辑）（全6册）', '柯南·道尔 著；厉河 编；余远锽 绘；海豚传媒出品', '2018-02-01', '湖北教育出版社', '114.00');
insert into book (name, author, year, publisher, price) VALUES ('细菌世界历险记（又名《灰尘的旅行》，小学语文快乐读书吧·四年级下阅读）[高士其经典科普故事传播科学知识，提升科学素养]', '高士其', '2018-02-05', '浙江工商大学出版社', '26.00');
insert into book (name, author, year, publisher, price) VALUES ('狂人日记：鲁迅小说全集（1938年复社底本，中国白话小说开山之作。收录鲁迅全部小说，多篇入选语文课本）', '鲁迅', '2021-08-01', '中国友谊出版公司', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('罗尔德·达尔作品典藏（彩图拼音版）—了不起的狐狸爸爸', '(英) 罗尔德·达尔 著； (英) 昆汀·布莱克绘；代维 译。', '2018-09-01', '明天出版社', '28.00');
insert into book (name, author, year, publisher, price) VALUES ('雪国（川端康成诺贝尔文学奖获奖作，全新精装典藏版）', '（日）川端康成 著， 新经典  出品', '2020-03-01', '南海出版公司', '49.00');
insert into book (name, author, year, publisher, price) VALUES ('科幻世界·三体Ⅱ·黑暗森林（典藏版）', '刘慈欣，科幻世界出品', '2016-06-30', '重庆出版社', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('瓦尔登湖(珍藏本) 朗读者朗读书目', '（美）梭罗    知书达礼  出品', '2010-12-01', '中国三峡出版社', '28.00');
insert into book (name, author, year, publisher, price) VALUES ('美国儿科学会育儿百科（第7版）', '美) 塔尼娅·奥尔特曼', '2020-12-01', '北京科学技术出版社', '108.00');
insert into book (name, author, year, publisher, price) VALUES ('我们仨（新版）', '杨绛', '2018-06-01', '生活.读书.新知三联书店', '28.00');
insert into book (name, author, year, publisher, price) VALUES ('稻草人（手绘精美插图）', '叶圣陶，小当当童书馆 出品', '2018-12-01', '安徽教育出版社', '19.80');
insert into book (name, author, year, publisher, price) VALUES ('挪威的森林（2018年新版，村上春树的残酷青春物语，现象级的超级畅销书，三十周年纪念版）', '【日】村上春树 林少华 译', '2018-03-01', '上海译文出版社', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('乌鸦面包店（全5册）', '（日）加古里子  著，爱心树童书 出品', '2021-06-01', '新星出版社', '138.00');
insert into book (name, author, year, publisher, price) VALUES ('阅读是一座随身携带的避难所（罗翔推荐版本。“阅读应该是愉悦的，怎么思考就有怎么样的人生”。）', '毛姆 著，夏高娃 译，果麦文化 出品', '2020-07-01', '江西人民出版社', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('红星照耀中国  青少版 八年级上册 人民文学出版社 团购电话4001066666转6', '埃德加·斯诺 著；董乐山 译', '2017-06-01', '人民文学出版社', '33.00');
insert into book (name, author, year, publisher, price) VALUES ('是谁嗯嗯在我的头上——邓超微博推荐的绘本 带给孩子更多勇气和自信的绘本！', '文：〔德〕维尔纳霍尔茨瓦特（WernerHolzwarth）　著，方素珍　译', '2019-11-01', '河北教育出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('论语译注（简体字本） 修订新版  《典籍里的中国》第五期隆重推出《论语》。央视CCTV-10《读书》栏目推荐中华书局十大好书之一。', '杨伯峻 译注', '2017-08-01', '中华书局', '26.00');
insert into book (name, author, year, publisher, price) VALUES ('月亮的味道（精装）', '麦克格雷涅茨 著', '2017-10-01', '二十一世纪出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('人生（2021版，茅盾文学奖得主路遥代表作，激励万千读者，堪称《平凡的世界》序篇））', '路遥  著 ，新经典  出品', '2021-07-01', '北京十月文艺出版社', '39.50');
insert into book (name, author, year, publisher, price) VALUES ('中国古代神话 山海经 希腊神话故事 四年级上册快乐读书吧推荐阅读（中小学生课外阅读指导丛书）套装共3册 41000多名读者热评！', '闻钟主编', '2019-06-01', '南方出版社', '80.40');
insert into book (name, author, year, publisher, price) VALUES ('野兽国 （凯迪克金奖绘本，莫里斯桑达克代表品）', '莫里斯桑达克  著  宋珮 译', '2014-06-01', '贵州人民出版社', '36.00');
insert into book (name, author, year, publisher, price) VALUES ('终身成长：重新定义成功的思维模式', '[美]卡罗尔·德韦克（Carol Dweck) ， 译者：楚祎楠   后浪', '2017-11-01', '江西人民出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('小猪唏哩呼噜(注音版上、下)', '孙幼军　著', '2014-07-01', '春风文艺出版社', '30.00');
insert into book (name, author, year, publisher, price) VALUES ('被欺负了，可以打回去吗（解决父母的世纪难题，告诉孩子被欺负了该怎么办，小杨叔叔送给3-6岁孩子的冲突教育绘本）', '小杨叔叔', '2021-07-01', '新世界出版社', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('山海经 快乐读书吧 四年级上册推荐阅读(中小学生课外阅读指导丛书)无障碍阅读 彩插励志版 5万多名读者热评！', '（晋）郭璞 注', '2019-06-01', '南方出版社', '32.80');
insert into book (name, author, year, publisher, price) VALUES ('你好！数学（超值礼品盒装，共30册）', '申惠恩　等文，赵美子　等图，仇艳　等译', '2012-04-01', '湖北少儿出版社', '240.00');
insert into book (name, author, year, publisher, price) VALUES ('居里夫人的故事 小学生儿童文学三四五六年级8-9-10-12岁课外阅读书籍青少年世界名著童话故事书彩图美绘版', '[英] 埃列娜·多丽', '2019-08-01', '北京日报出版社（原同心出版社）', '19.80');
insert into book (name, author, year, publisher, price) VALUES ('失落的卫星：深入中亚大陆的旅程（得到年度好书，某瓣中文非小说top 1，罗新、许知远力荐！单向街年度青年作家，记录被遗忘的人）', '刘子超  著 ， 新经典  出品', '2020-06-01', '文汇出版社', '69.00');
insert into book (name, author, year, publisher, price) VALUES ('魔法拼音国 【升级版 全彩共10册】（7册故事绘本+3册闯关游戏+100张字母纸牌+配套音频，寓教于乐，让学拼音变成一件快乐的事！）', '姜自霞', '2020-01-01', '浙江少年儿童出版社', '138.00');
insert into book (name, author, year, publisher, price) VALUES ('原则 principles 雷·达里奥著 跨年演讲推荐图书 团购电话:4001066666转6', '[美]瑞·达利欧（Ray Dalio）', '2018-01-01', '中信出版社', '98.00');
insert into book (name, author, year, publisher, price) VALUES ('人生只有一件事:教你如何活得更好', '金惟纯', '2021-05-13', '中信出版社', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('易经的奥秘：完整版', '曾仕强', '2017-07-10', '北京时代华文书局', '64.00');
insert into book (name, author, year, publisher, price) VALUES ('小熊很忙 小达人点读版 第1辑（套装共4册）深海潜水员+小小宇航员+动物管理员+圣诞小帮手', 'Benji Davies', '2019-06-01', '中信出版社', '180.00');
insert into book (name, author, year, publisher, price) VALUES ('放学后（东野圭吾成名作）', '〔日〕东野圭吾 著，新经典 出品', '2017-09-01', '南海出版公司', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('人间词话（王国维先生的代表作，近代较富盛名的词话著作）', '王国维　著', '2015-06-01', '北京联合出版公司', '29.80');
insert into book (name, author, year, publisher, price) VALUES ('米小圈上学记四年级（套装共4册）', '北猫', '2018-04-01', '四川少儿出版社', '100.00');
insert into book (name, author, year, publisher, price) VALUES ('中国民间故事 快乐读书吧 五年级上册推荐阅读(中小学生课外阅读指导丛书)无障碍阅读 彩插励志版 75000多名读者热评！', '闻钟主编', '2019-06-01', '南方出版社', '22.80');
insert into book (name, author, year, publisher, price) VALUES ('【2019诺贝尔经济学奖得主作品】 贫穷的本质（修订版）：我们为什么摆脱不了贫穷', '（印度）阿比吉特.班纳吉(Abhijit V.Banerjee)、（法）埃斯特.迪弗洛(Esther Duflo)', '2018-09-01', '中信出版社', '58.00');
insert into book (name, author, year, publisher, price) VALUES ('焦虑的人（九个焦虑的人，一场人质劫持，能解救他们的不是警察，而是彼此。《外婆的道歉信》《清单人生》巴克曼拿手的暖心治愈故事）', '[瑞典]弗雷德里克·巴克曼，译者 孙璐，果麦文化 出品', '2021-08-01', '天津人民出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('我不敢说，我怕被骂——邓超微博推荐的绘本 带给孩子更多勇气和自信的绘本！', '文：〔荷兰〕皮姆?范?赫斯特  图：〔荷兰〕妮可?塔斯马', '2019-11-01', '北京联合出版公司', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('速成围棋 入门篇 上', '黄焰 金成来', '2011-11-01', '青岛出版社', '25.00');
insert into book (name, author, year, publisher, price) VALUES ('学会爱自己（情绪管理篇）提升自控力、分辨力！不为坏人保守秘密，不随便顺从别人！学会保护自己，做对自己负责的主人', '艾迪特·史莱博·维克（奥），达格玛·盖斯勒（德）著，张清泉，尔矣 译', '2015-08-10', '青岛出版社', '98.00');
insert into book (name, author, year, publisher, price) VALUES ('你就是孩子最好的玩具樊登导读 樊登博士的育儿成功之道，五步情感引导法，奠定父母与孩子一生的亲密关系。百万中国妈妈五星好评！', '金伯莉·布雷恩', '2021-05-01', '南方出版社', '46.00');
insert into book (name, author, year, publisher, price) VALUES ('论语（国学启蒙经典系列。全文注音+详尽注释+精准翻译，无需古文基础，也能轻松读懂）', '张圣洁 主编；闫立君、刘汛涛 副主编', '2019-01-01', '浙江教育出版社', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('中华人民共和国民法典（实用版）2021年1月起正式施行  团购电话：4001066666转6', '中国法制出版社', '2020-06-01', '中国法制出版社', '65.00');
insert into book (name, author, year, publisher, price) VALUES ('岛上书店（李现推荐，每个人的生命中，都有无比艰难的那一年，将人生变得美好而辽阔。加·泽文感动读者的治愈小说！）', '(美)加·泽文 著；读客文化 出品', '2015-05-08', '江苏文艺出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('朝花夕拾（未删减版） 七年级上 人教版名著阅读课程化丛书 教材推荐书目 人民教育出版社（入选中小学生阅读指导目录 推荐阅读）', '鲁迅 著', '2017-06-01', '人民教育出版社', '22.80');
insert into book (name, author, year, publisher, price) VALUES ('幼儿学古诗（绘本版，全2册）', '中国教育科学研究院学前教育研究中心', '2019-08-08', '教育科学出版社有限公司', '98.00');
insert into book (name, author, year, publisher, price) VALUES ('思考，快与慢（团购电话400-106-6666转6）', '(美)丹尼尔·卡尼曼', '2012-07-01', '中信出版社', '69.00');
insert into book (name, author, year, publisher, price) VALUES ('我喜欢生命本来的样子(周国平经典散文作品集)', '周国平', '2017-02-01', '作家出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('绝叫（罗翔推荐，长达四十年的恶女编年史，日本文学社会派推理小说 同名日剧《绝叫》原著）', '叶真中显 著 林佩瑾 译 联合读创 出品', '2020-07-01', '北京联合出版有限公司', '58.00');
insert into book (name, author, year, publisher, price) VALUES ('青鸟 小学生儿童文学三四五六年级8-9-10-12岁课外阅读书籍青少年世界名著童话故事书彩图美绘版', '莫里斯·梅特林克', '2019-08-01', '北京日报出版社（原同心出版社）', '19.80');
insert into book (name, author, year, publisher, price) VALUES ('皮特猫·3~6岁好性格养成书：共四辑（套装1~4辑）（乐观、自信、抗挫……荣获19项大奖的好性格榜样，在美国家喻户晓）', '詹姆斯·迪安等 著；彭懿,余治莹等 译；读客文化 出品', '2018-08-17', '文汇出版社', '559.60');
insert into book (name, author, year, publisher, price) VALUES ('牧羊少年奇幻之旅（央视《朗读者》、湖南卫视《天天向上》、李现、黄轩、TFBOYS、高圆圆推荐，能改变一个人一生的书）', '（巴西）保罗·柯艾略 著，新经典 出品', '2018-01-01', '北京十月文艺出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('崔玉涛育儿百科', '崔玉涛', '2018-12-31', '中信出版社', '178.00');
insert into book (name, author, year, publisher, price) VALUES ('一年级的小豌豆+一年级的小蜜瓜（全彩注音版套装共2册）', '商晓娜', '2019-01-01', '青岛出版社', '76.00');
insert into book (name, author, year, publisher, price) VALUES ('这就是二十四节气：升级版 全四册(文津图书奖获奖图书，销量逾300万册，当当网畅销好书、口碑童书。)', '高春香、邵敏/著；许明振、李婧/绘', '2019-11-01', '海豚出版社', '150.00');
insert into book (name, author, year, publisher, price) VALUES ('365夜睡前故事（全4册） 宝宝睡前故事书0-3-6岁幼儿故事书早教配图 婴儿绘本书籍 [0-6岁]', '青葫芦', '2018-01-01', '福建科技出版社', '67.20');
insert into book (name, author, year, publisher, price) VALUES ('向上生长（九边作品。让选择变得精准，让机遇不再错失。 悉数解决人生困惑问题，实现向上生长。）', '九边 著；书田文化出品，有容书邦发行', '2020-05-06', '贵州人民出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('晚安，大猩猩', '（美） 佩吉·拉特曼 著， 爱心树童书  出品', '2019-04-01', '北京联合出版有限公司', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('世界博物馆奇妙之旅（全5册，为孩子打造的博物通识启蒙绘本）', '徐晓燕 黄纷纷 蒋佳宁 著，布克布克 绘，小当当童书馆 出品', '2019-08-01', '浙江教育出版社', '108.00');
insert into book (name, author, year, publisher, price) VALUES ('这就是化学（全8册）畅销书《这就是物理》姊妹篇', '米莱童书', '2020-12-01', '四川教育出版社', '200.00');
insert into book (name, author, year, publisher, price) VALUES ('梅格时空大冒险·7~14岁儿童文学科幻经典（全5册）银河的裂缝 等5册儿童文学史上家喻户晓、不可逾越的经典', '(美)马德琳·英格 著；读客文化 出品', '2017-07-01', '文汇出版社', '216.80');
insert into book (name, author, year, publisher, price) VALUES ('流浪的地球（《三体》作者刘慈欣绚丽想象力之作，大人孩子均可阅读。)', '刘慈欣 著，小当当童书馆 出品', '2018-05-01', '浙江教育出版社', '29.00');
insert into book (name, author, year, publisher, price) VALUES ('自己的颜色', '李欧·李奥尼', '2011-05-01', '南海出版公司', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('我喜欢自己——邓超微博推荐的绘本 带给孩子更多勇气和自信的绘本！', '（美）卡尔森　著，余治莹　译', '2019-11-01', '河北教育出版社', '35.80');
insert into book (name, author, year, publisher, price) VALUES ('人类群星闪耀时（无删减全译本。《一个陌生女人的来信》作者茨威格的传记杰作，14位时代英雄，14个人类命运攸关的历史时刻）', '〔奥〕斯蒂芬·茨威格 著，潘子力 高中甫 译', '2018-01-15', '时代文艺出版社', '28.00');
insert into book (name, author, year, publisher, price) VALUES ('哈利·波特与魔法石（《语文》教材推荐阅读书目，外国儿童文学经典，新英国版封面平装版）', '（英）J.K.罗琳', '2018-11-01', '人民文学出版社', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('海豚绘本花园：会飞的挖土机（平）', '[英]伊恩?威柏', '2016-12-01', '长江少年儿童出版社', '22.00');
insert into book (name, author, year, publisher, price) VALUES ('父与子全集完整版彩色注音版小学生课外阅读书籍一二年级带拼音绘本漫画书儿童幽默搞笑故事书语文阅读名著文学儿童书籍7-8-9-10周岁', '埃·奥·卜劳恩绘', '2018-08-01', '东北师范大学出版社', '29.80');
insert into book (name, author, year, publisher, price) VALUES ('狼王梦（升级版）/动物小说大王沈石溪·品藏书系', '沈石溪', '2018-07-01', '浙江少年儿童出版社', '26.00');
insert into book (name, author, year, publisher, price) VALUES ('如果历史是一群喵8·盛世大唐篇', '肥志 编绘；漫友文化出品', '2021-05-25', '广东旅游出版社', '59.80');
insert into book (name, author, year, publisher, price) VALUES ('一只特立独行的猪（有趣、独立、反对假正经，读王小波的“入坑之选”！依据王小波手稿、生前定稿修订多年讹误，SHOU度以读者视角排定蕞佳阅读顺序。）', '王小波  著 ， 新经典  出品', '2021-01-01', '北京十月文艺出版社', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('可复制的领导力：樊登的9堂商业课（团购，请致电400-106-6666转6）', '樊登', '2017-12-01', '中信出版社', '49.00');
insert into book (name, author, year, publisher, price) VALUES ('父与子全集（全彩版。一代幽默大师卜劳恩的爆笑暖心漫画）', '[德] 埃·奥·卜劳恩  绘', '2017-04-01', '浙江工商大学出版社', '36.00');
insert into book (name, author, year, publisher, price) VALUES ('神奇校车·动画版（全10册）', '作者:乔安娜柯尔 著,布鲁斯迪根 绘 , 漆仰平 译', '2011-04-05', '贵州人民出版社', '118.00');
insert into book (name, author, year, publisher, price) VALUES ('学习高手（90后哈佛耶鲁高分毕业生超实用学习法）', '李柘远 著，磨铁图书 出品', '2020-08-01', '北京联合出版有限公司', '55.00');
insert into book (name, author, year, publisher, price) VALUES ('果麦经典：了凡四训（“我命由我不由天！”曾国藩、胡适、稻盛和夫推崇的生活方式手册；费勇教授精美译文）', '袁了凡 著，译者 费勇，果麦文化 出品', '2017-09-01', '三秦出版社', '32.00');
insert into book (name, author, year, publisher, price) VALUES ('【赠4张人物卡片+笔记本】 漫画百年党史·开天辟地（混知团队半小时系列之后的重磅力作 让你轻松学党史）', '陈磊·混知团队  陈晋', '2021-09-01', '浙江人民出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('红岩', '罗广斌，杨益言', '2017-09-01', '中国青年出版社', '36.00');
insert into book (name, author, year, publisher, price) VALUES ('中国历代政治得失 钱穆（新校本）', '钱穆　著', '2013-12-28', '九州出版社', '16.00');
insert into book (name, author, year, publisher, price) VALUES ('人类群星闪耀时（14个改变人类命运的天才，14个影响人类文明的瞬间！全新精装彩插导读详注版！）（读客经典文库）', '(奥地利)茨威格 著；读客文化 出品', '2019-04-01', '江苏凤凰文艺出版社', '69.00');
insert into book (name, author, year, publisher, price) VALUES ('德鲁克 卓有成效的管理者', '[美]彼得.德鲁克（Peter F. Drucker）', '2019-04-20', '机械工业出版社', '69.00');
insert into book (name, author, year, publisher, price) VALUES ('米小圈上学记三年级（套装共4册）', '北猫', '2018-04-01', '四川少儿出版社', '100.00');
insert into book (name, author, year, publisher, price) VALUES ('穆斯林的葬礼（2015版）', '霍达　著，新经典 出品', '2015-09-01', '北京十月文艺出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('小飞侠彼得·潘（小女孩小男孩的成长故事，奇幻+幽默+满满的爱。《哈利·波特》作者罗琳在奥运会开幕式上倾情朗诵）', '〔英〕詹姆斯·巴里  著   张炽恒  译', '2017-06-01', '浙江工商大学出版社', '20.00');
insert into book (name, author, year, publisher, price) VALUES ('捣蛋鬼日记 小学生儿童文学三四五六年级8-9-10-12岁课外阅读书籍青少年世界名著童话故事书彩图美绘版', '[意大利] 万巴', '2019-08-01', '北京日报出版社（原同心出版社）', '19.80');
insert into book (name, author, year, publisher, price) VALUES ('下沉年代（“得到”年度好书，许倬云、刘擎、但斌一致推荐！呈现美国近三十年沧桑巨变的史诗作品，每一个向上奋斗者的之书）', '（美）乔治·帕克  著  ，新经典   出品', '2021-01-01', '文汇出版社', '108.00');
insert into book (name, author, year, publisher, price) VALUES ('置身事内：中国政府与经济发展（罗永浩、刘格菘、张军、周黎安、王烁联袂推荐，复旦经院“毕业课”）团购电话:4001066666转6', '兰小欢 著', '2021-08-01', '上海人民出版社', '65.00');
insert into book (name, author, year, publisher, price) VALUES ('自驱型成长：如何科学有效地培养孩子的自律', '[美]威廉?斯蒂克斯鲁德（William Stixrud）奈德?约翰逊（Ned Johnson）、叶壮 译', '2020-05-15', '机械工业出版社', '75.00');
insert into book (name, author, year, publisher, price) VALUES ('把坏脾气收起来', '〔美〕卡罗尔·罗思，（美）拉申·凯里耶', '2017-08-01', '北京科学技术出版社', '36.00');
insert into book (name, author, year, publisher, price) VALUES ('一粒种子的旅行', '（德）安妮·默勒 著， 爱心树童书  出品', '2017-06-01', '南海出版公司', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('朱自清散文集', '朱自清', '2020-05-01', '海燕出版社', '28.00');
insert into book (name, author, year, publisher, price) VALUES ('审判（卡夫卡长篇代表作之一。钱满素、袁华清翻译）', '〔奥〕卡夫卡 著；钱满素 袁华清  译', '2018-04-01', '时代文艺出版社', '25.00');
insert into book (name, author, year, publisher, price) VALUES ('假如给我三天光明（中小学生阅读指导目录5-6年级。海伦·凯勒在逆境中创造奇迹的伟大自传，她被《时代周刊》评为20世纪美国十大英雄偶像之一）', '（美）凯勒　著，吴君芳，王一凡　译', '2015-01-01', '安徽教育出版社', '18.00');
insert into book (name, author, year, publisher, price) VALUES ('不可思议的旅程三部曲（2020版）', '（美）艾伦·贝克尔 著，爱心树童书 出品', '2020-08-01', '新星出版社', '179.40');
insert into book (name, author, year, publisher, price) VALUES ('把自己当回事儿（杨天真的沟通秘籍！蔡康永、樊登、罗永浩真挚推荐，李诞、马伊琍、脱不花诚意作序。）', '杨天真', '2021-04-01', '北京联合出版有限公司', '56.00');
insert into book (name, author, year, publisher, price) VALUES ('逛动物园是件正经事 向往的生活书单  自然感悟动物园里的博物学宝典知名媒体人张腾岳多家动物园园长联名推', '花蚀', '2020-01-01', '商务印书馆', '98.00');
insert into book (name, author, year, publisher, price) VALUES ('存在主义心理治疗(心理治疗译丛)', '[美]欧文·D. 亚隆 著  黄峥 张怡玲 沈东郁 译', '2015-06-01', '商务印书馆', '99.00');
insert into book (name, author, year, publisher, price) VALUES ('吴军阅读与写作讲义（文津图书奖得主、硅谷投资人吴军重磅新作，助力你构建理解他人、表达自我的能力，别让短板伴随你一生）', '吴军 著; 得到图书 出品', '2021-04-15', '新星出版社', '99.00');
insert into book (name, author, year, publisher, price) VALUES ('特工训练手册 危急时刻如何绝处逢生', '[美]克林特·埃默森（Clint Emerson），译者：诸葛雯      后浪', '2020-11-08', '九州出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('王阳明传习录（典籍里的中国推荐 全译全注，明隆庆六年初刻版，原貌重现初始定本，附录并译注王阳明亲自编定的《朱子晚年定论》）', '王阳明 著；读客文化 出品', '2015-07-01', '江苏文艺出版社', '36.00');
insert into book (name, author, year, publisher, price) VALUES ('丰乳肥臀（莫言用情极深的长篇代表作，女性苦难史）', '莫言', '2020-03-01', '浙江文艺出版社', '69.00');
insert into book (name, author, year, publisher, price) VALUES ('爱心树（2018版）', '（美）谢尔·希尔弗斯坦  著绘， 爱心树童书  出品', '2018-01-01', '北京联合出版有限公司', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('第一次自己睡觉——父母教孩子自己睡觉首选绘本（启发童书馆出品）', '文：（日）季巳明代 著  图：（日）长谷川香子 绘', '2019-12-01', '北京联合出版公司', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('薛兆丰经济学讲义', '薛兆丰', '2018-07-01', '中信出版社', '68.00');
insert into book (name, author, year, publisher, price) VALUES ('没头脑和不高兴 任溶溶幽默儿童文学创作（注音版）典藏本', '任溶溶', '2018-04-01', '浙江少年儿童出版社', '98.00');
insert into book (name, author, year, publisher, price) VALUES ('爱丽丝漫游奇境记（经典插图本，语文教材“快乐读书吧”六年级下阅读。哈利波特系列译者马爱农翻译）', '[英]刘易斯·卡罗尔  著,马爱农 译.', '2016-11-01', '北京联合出版公司', '18.00');
insert into book (name, author, year, publisher, price) VALUES ('沧浪之水（某瓣8.5分，入围茅盾文学奖。职场小白、考公人的启蒙之书。2021版）', '阎真  著 ， 新经典  出品', '2021-07-01', '北京十月文艺出版社', '49.00');
insert into book (name, author, year, publisher, price) VALUES ('遥远的救世主+天幕红尘+天局（《遥远的救世主》即《背叛》，一套读懂世界，豆豆矫健三部曲）', '豆豆 矫健 著', '2020-07-22', '作家出版社', '134.00');
insert into book (name, author, year, publisher, price) VALUES ('悉达多（译者姜乙翻译）【果麦经典】', '[德]赫尔曼·黑塞，译者：姜乙，果麦文化 出品', '2017-01-01', '天津人民出版社', '32.00');
insert into book (name, author, year, publisher, price) VALUES ('出发，刷牙小火车', '〔日〕久保真知子◎著; 凌文桦◎译', '2017-05-01', '北京科学技术出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('小威向前冲', '[美]尼古拉斯·艾伦 著；漆仰平 译', '2018-04-23', '贵州人民出版社', '36.00');
insert into book (name, author, year, publisher, price) VALUES ('苏世民：我的经验与教训', '苏世民', '2020-03-01', '中信出版社', '98.00');
insert into book (name, author, year, publisher, price) VALUES ('第一次上街买东西', '（日）筒井赖子 著 ，（日）林明子 绘，爱心书童书 出品', '2020-06-01', '新星出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('薇娅推荐 陪孩子终身成长（樊登2020年新书！）', '樊登', '2020-04-01', '中国友谊出版公司', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('嫦娥探月立体书', '王倩 宁远明 马莉 李雷雷 文，王晓旭 图，乐乐趣出版', '2018-09-01', '陕西人民教育出版社', '138.00');
insert into book (name, author, year, publisher, price) VALUES ('捕捉儿童敏感期 孙瑞雪 （精装珍藏版）', '孙瑞雪', '2013-04-01', '中国妇女出版社', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('古文观止（上下册，原文+导读+注释+翻译，特别适合青少年）', '[清]吴楚材，吴调侯 编  钱素洲 译', '2016-09-01', '浙江教育出版社', '52.00');
insert into book (name, author, year, publisher, price) VALUES ('安徒生童话（小学语文“快乐读书吧”·三年级上阅读，叶君健先生翻译）', '［丹］安徒生　著 ，叶君健　译', '2015-05-01', '安徽教育出版社', '20.00');
insert into book (name, author, year, publisher, price) VALUES ('李玫瑾：幽微的人性+心理抚养（套装共2册）', '李玫瑾', '2021-05-01', '上海三联书店', '86.60');
insert into book (name, author, year, publisher, price) VALUES ('三毛流浪记（彩图注音读物）', '张乐平   著', '2017-06-01', '少年儿童出版社', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('牙婆婆 （儿童医师张思莱倾情推荐。愉快教导孩子保护牙齿的妈妈书！小朋友，你喜欢甜食吗？吃过甜食，你有好好刷牙吗？送给爱吃甜食的你！）', '苅田澄子 著 冈部理香 绘', '2016-12-01', '北京联合出版公司', '36.00');
insert into book (name, author, year, publisher, price) VALUES ('西尔斯怀孕百科（全新升级典藏版）', '威廉·西尔斯 等 著 ， 新经典   出品', '2019-03-01', '南海出版公司', '88.00');
insert into book (name, author, year, publisher, price) VALUES ('无声告白（我们终此一生，就是要摆脱他人的期待，找到真正的自己。就是她！征服欧美文坛的华裔作家伍绮诗！）', '(美)伍绮诗 著,孙璐 译；读客文化 出品', '2016-09-01', '江苏文艺出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('张泉灵的作文课 想象+观察（第一辑）（共两册）', '张泉灵', '2021-07-06', '中信出版社', '99.60');
insert into book (name, author, year, publisher, price) VALUES ('神奇的逻辑思维游戏书', '【日】索尼国际教育公司 著，阳光博客 出品', '2018-10-01', '北京日报出版社（原同心出版社）', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('小黑鱼', '李欧·李奥尼， 爱心树童书  出品', '2010-01-01', '南海出版公司', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('道德经 精装珍藏本', '（春秋）老子著；富强译 注，高高国际  出品', '2016-06-30', '作家出版社', '32.80');
insert into book (name, author, year, publisher, price) VALUES ('疯人说：精神病院医生手记', '穆戈', '2021-06-20', '金城出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('张爱玲全集02：红玫瑰与白玫瑰（精装典藏版）', '张爱玲  著 ， 新经典  出品', '2019-01-01', '北京十月文艺出版社', '49.50');
insert into book (name, author, year, publisher, price) VALUES ('我与地坛（纪念版）', '史铁生', '2011-06-01', '人民文学出版社', '29.00');
insert into book (name, author, year, publisher, price) VALUES ('亲密关系（第6版）', '罗兰·米勒 ， 新曲线 出品', '2015-07-01', '人民邮电出版社', '138.00');
insert into book (name, author, year, publisher, price) VALUES ('小羊上山儿童汉语分级读物（第1级、2级、3级）(30册套装)', '孙蓓主编,童趣出版有限公司编', '2021-04-01', '人民邮电出版社', '454.00');
insert into book (name, author, year, publisher, price) VALUES ('月亮和六便士（毛姆代表作之一，全新导读+无删节详注版）', '〔英〕毛姆 著  苏福忠 译', '2017-09-01', '时代文艺出版社', '27.00');
insert into book (name, author, year, publisher, price) VALUES ('睡睡镇+超级跑跑镇（套装共2册）', '亚东/文 麦克小奎/图', '2019-11-19', '中信出版社', '78.00');
insert into book (name, author, year, publisher, price) VALUES ('人性的因素（张艺兴书单，向往的生活止庵史航推荐！被马尔克斯誉为完美的小说。格林是21次诺贝尔文学奖提名的文学大师！）', '（英）格雷厄姆·格林(Graham Greene)  著；韦清琦 译；读客文化 出品', '2018-11-30', '江苏文艺出版社', '65.00');
insert into book (name, author, year, publisher, price) VALUES ('古汉语常用字字典（第5版）', '原编者  王力 岑麒祥 林焘 等，修订者  蒋绍愚 唐作藩 张万起 等', '2016-04-01', '商务印书馆', '39.90');
insert into book (name, author, year, publisher, price) VALUES ('万历十五年 一本好书 腾讯视频栏目推荐', '黄仁宇', '2006-06-01', '生活.读书.新知三联书店', '26.00');
insert into book (name, author, year, publisher, price) VALUES ('奇先生妙小姐全译本（共90册）', '罗杰·哈格里维斯', '2020-10-01', '人民邮电出版社', '498.00');
insert into book (name, author, year, publisher, price) VALUES ('白鹿原', '陈忠实', '2017-10-01', '人民文学出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('泰戈尔诗集：新月集·飞鸟集（泰戈尔诗选+《泰戈尔传》。语文教材“名著导读”经典·九年级上）', '(印) 泰戈尔 著，郑振铎  译', '2018-04-09', '浙江工商大学出版社', '21.00');
insert into book (name, author, year, publisher, price) VALUES ('养育男孩（典藏版）', '(澳) 史蒂夫·比达尔夫', '2019-09-10', '中信出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('元宇宙＋元宇宙通证（全2册）（揭秘下一代互联网新态势，探索VR全景新场景，全面呈现元宇宙知识谱系，权威阐述未来新世界）', '赵国栋、易欢欢、徐远重、邢杰、余晨 等 著/编著', '2021-08-01', '中译出版社（原中国对外翻译出版公司）', '113.00');
insert into book (name, author, year, publisher, price) VALUES ('好饿的小蛇（ 绘本大师宫西达也低幼绘本代表作）', '文/图 宫西达也，译 彭懿', '2007-05-01', '２１世纪出版社', '32.00');
insert into book (name, author, year, publisher, price) VALUES ('逻辑学入门：清晰思考、理性生活的88个逻辑学常识', '格桑', '2020-09-01', '中国纺织出版社', '42.80');
insert into book (name, author, year, publisher, price) VALUES ('十二生肖的故事——首届丰子恺儿童图画书奖得主  赖马作品！', '文/图：赖马', '2020-03-28', '河北教育出版社', '45.80');
insert into book (name, author, year, publisher, price) VALUES ('姜小牙上学记（套装共4册）', '北猫', '2017-10-01', '四川少儿出版社', '90.00');
insert into book (name, author, year, publisher, price) VALUES ('时间简史（插图本）（央视《朗读者》推荐）', '史蒂芬·霍金', '2014-06-01', '湖南科技出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('午夜降临前抵达（当当专享签章本，李健、梁文道、麦家、许知远、俞敏洪推荐，不能出远门的日子，你需要一本旅行文学，附赠精美路线图）', '刘子超  著，新经典  出品', '2021-08-01', '文汇出版社', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('深见春夫超级想象力图画书（全15册）', '深见春夫', '2019-05-15', '电子工业出版社', '297.00');
insert into book (name, author, year, publisher, price) VALUES ('信谊原创图画书系列-团圆', '作者:余丽琼　文，朱成梁　绘', '2008-04-01', '明天出版社', '45.80');
insert into book (name, author, year, publisher, price) VALUES ('这里是中国 2019年度中国好书 文津图书奖获奖作品', '星球研究所，中国青藏高原研究会', '2019-09-01', '中信出版社', '168.00');
insert into book (name, author, year, publisher, price) VALUES ('许三观卖血记（新版）', '余华', '2017-09-12', '作家出版社', '32.00');
insert into book (name, author, year, publisher, price) VALUES ('全球最美的100个地方 图说天下 国家地理', '&lt;图说天下.国家地理系列&gt;编委会', '2012-06-01', '北京联合出版公司', '19.90');
insert into book (name, author, year, publisher, price) VALUES ('金字塔原理大全集（共2册）（思考表达和解决问题的逻辑，“抖音同款”麦肯锡40年经典培训教材）', '芭芭拉 · 明托  著  ， 新经典  出品', '2019-07-01', '南海出版公司', '176.00');
insert into book (name, author, year, publisher, price) VALUES ('漫画讲透孙子兵法(全4册)（130个知识点讲透5000字原文，130场战斗像看战争大片一样精彩震撼！全新青少年读本，300幅漫画贯穿全书！）', '华杉 著；读客文化 出品', '2020-04-16', '江苏凤凰文艺出版社', '147.20');
insert into book (name, author, year, publisher, price) VALUES ('拉塞-玛娅侦探所 第一辑(全10册）', '马丁·维德马克/著；海伦娜·威利斯/绘；小博集出品；', '2021-02-01', '湖南文艺出版社', '178.00');
insert into book (name, author, year, publisher, price) VALUES ('谁说一定要用蓝色画天空·3~6岁创造力绘本（鼓励孩子“乱”画，创造力就能无限大！鼓励孩子创造、挖掘孩子天赋的上佳选择！）', '(加) 彼得.雷诺兹  著；读客文化 出品', '2020-04-22', '文汇出版社', '42.80');
insert into book (name, author, year, publisher, price) VALUES ('小狗钱钱2', '博多·舍费尔', '2018-05-01', '四川少儿出版社', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('袜子藏哪儿了', '五味太郎 著', '2018-07-01', '北京联合出版有限公司', '28.00');
insert into book (name, author, year, publisher, price) VALUES ('快乐读书吧四年级上册：中国古代神话+希腊神话故事+山海经（共3册）', '（德）古斯塔夫·施瓦布著 斑马爱读书主编', '2019-08-01', '黑龙江少年儿童出版社', '59.40');
insert into book (name, author, year, publisher, price) VALUES ('昆虫记（语文教材“名著导读”经典·八年级上。内容更丰富版本：33张彩色照片图+系统分类目录+昆虫谱系表+大量详注+颠覆性纠错，帮你构筑系统的知识体系）', '[法]让-亨利·法布尔  著    陈筱卿  译', '2017-09-01', '时代文艺出版社', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('儒林外史(56回全本，内容考证、文字句读全新修订版)', '吴敬梓', '2015-07-01', '花山文艺出版社', '25.00');
insert into book (name, author, year, publisher, price) VALUES ('刑法学讲义（罗翔普法故事会，拆穿生活的套路，看透舆论的陷阱，人人都能拥有法学智慧。人民日报、央视激赏推荐，千万读者好评）', '罗翔，果麦文化 出品', '2020-07-01', '云南人民出版社', '68.00');
insert into book (name, author, year, publisher, price) VALUES ('二十四节气自然绘本 让孩子了解自然的瞬息万变 科普百科绘本', '肖克之', '2020-08-01', '北京联合出版有限公司', '79.90');
insert into book (name, author, year, publisher, price) VALUES ('阿勒泰的角落（李娟成名作四色典藏版）', '李娟 著，新经典 出品', '2013-09-01', '新星出版社', '36.00');
insert into book (name, author, year, publisher, price) VALUES ('我的大喊大叫的一天', '瑞贝卡·帕特 著，孙昱 译', '2015-08-01', '新世纪出版社', '36.00');
insert into book (name, author, year, publisher, price) VALUES ('鼠小弟爱数学', '[美]埃莉诺·梅等 著 [美]德博拉·梅尔蒙 绘， 爱心树童书 出品', '2019-09-30', '江苏凤凰少年儿童出版社', '168.00');
insert into book (name, author, year, publisher, price) VALUES ('大卫科波菲尔（狄更斯传奇自传性小说，翻译家宋兆霖全译本）', '[英] 查尔斯·狄更斯 著, 宋兆霖 译', '2015-08-01', '作家出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('字母表谜案（怪异君推荐！当你隐隐觉得不对劲，致命的恶意正悄悄逼近！大山诚一郎封神之作！）（客悬疑文库）', '[日]大山诚一郎 著；读客文化 出品', '2021-04-30', '河南文艺出版社', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('名著名译名绘版（精装10册）', '马克 吐温　等著', '2015-01-01', '接力出版社', '980.00');
insert into book (name, author, year, publisher, price) VALUES ('歪歪兔行为习惯系列互动图画书（全10册）', '歪歪兔关键期早教项目组　编绘', '2015-08-18', '海豚出版社', '90.00');
insert into book (name, author, year, publisher, price) VALUES ('沙丘（同名电影即将全国上映！《降临》导演执导、“甜茶”“灭霸”“海王”、张震等主演。每个“不可不读”的书单上都有《沙丘》）', '(美)弗兰克.赫伯特 著；读客文化 出品', '2016-12-28', '江苏文艺出版社', '68.00');
insert into book (name, author, year, publisher, price) VALUES ('如果你坐得歪歪扭扭', '（韩）李仑姬', '2021-07-01', '北京科学技术出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('房思琪的初恋乐园 （专享限量手册）', '林奕含', '2018-01-02', '北京联合出版有限公司', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('森林报 春/夏/秋/冬（精美插图）', '（苏）比安基 ；小当当童书馆 出品', '2019-01-01', '安徽教育出版社', '91.20');
insert into book (name, author, year, publisher, price) VALUES ('中国古代文化常识 （插图修订第4版）', '王力 主编   后浪', '2014-11-01', '北京联合出版公司', '60.00');
insert into book (name, author, year, publisher, price) VALUES ('雷雨（中国现代杰出剧作家曹禺的代表作，被翻译成各国语言的中国话剧，精装收藏版）', '曹禺 著，新经典 出品', '2017-12-01', '北京十月文艺出版社', '36.00');
insert into book (name, author, year, publisher, price) VALUES ('读图识中国  入选中小学生阅读指导目录 阅读', '人民教育出版社地图编辑室　编', '2009-03-01', '人民教育出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('了不起的我：自我发展的心理学（陈海贤重磅新作，得到付费用户亲测有效 ）', '陈海贤 著; 得到图书 出品', '2019-11-01', '台海出版社', '69.00');
insert into book (name, author, year, publisher, price) VALUES ('飘（上下） 世界名著典藏', '（美）米切尔 著，黄健人 译 万亭文化 出品', '2015-02-01', '中央编译出版社', '50.00');
insert into book (name, author, year, publisher, price) VALUES ('人生由我：比“硅谷钢铁侠”埃隆·马斯克更酷的硬核母亲。励志版“向前一步”', '[加]梅耶·马斯克（Maye Musk） 著，代晓 译', '2020-06-01', '中信出版社', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('全球通史:从史前史到21世纪（第7版修订版上下册，赠送全球通史主题笔记本）', '（美）斯塔夫里阿诺斯  著，吴象婴  等译', '2006-10-01', '北京大学出版社', '96.00');
insert into book (name, author, year, publisher, price) VALUES ('大卫，不可以——1998年《纽约时报》年度最佳图画书  美国凯迪克大奖经典儿童绘本（启发童书馆出品）', '文/图：〔美〕大卫·香农David Shannon', '2019-04-08', '河北教育出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('学会爱自己（安全意识篇）防性侵、防诱拐！儿童安全教育图画书！让孩子学会保护自己！含《不要随便摸我》《不要随便亲我》《不要随便跟陌生人走》', '（美）珊蒂 克雷文 等  著，（美）茱蒂 柏斯玛等  绘，刘敏 译', '2017-09-10', '青岛出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('信谊宝宝起步走-好饿的毛毛虫（纸板书）', '[美] 艾瑞·卡尔 著，郑明进 译', '2018-05-01', '明天出版社', '42.80');
insert into book (name, author, year, publisher, price) VALUES ('笑场（全书新增40000字，李诞全新精装纪念版！）', '李诞', '2020-04-01', '北京联合出版有限公司', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('安的种子', '王早早 著，黄丽 绘', '2015-01-01', '海燕出版社', '29.80');
insert into book (name, author, year, publisher, price) VALUES ('非暴力沟通的父母话术 父母的语言养育男孩女孩正面管教儿童心理学训练手册亲子关系家庭教育孩子育儿书籍畅销书', '李少聪', '2020-09-01', '天津科学技术出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('一看就会的思维导图启蒙绘本（歪歪兔童书馆出品）', '歪歪兔关键期早教 项目组编绘', '2019-04-30', '海豚出版社', '128.00');
insert into book (name, author, year, publisher, price) VALUES ('资治通鉴少年简读版(套装全4册）附赠音频，扫码畅听！四册盒装，精华简读；史家打造，全彩插图！', '何孝荣 侯振龙', '2019-05-01', '青岛出版社', '156.00');
insert into book (name, author, year, publisher, price) VALUES ('见识城邦·娱乐至死', '（美）波兹曼　著，章艳　译', '2015-05-01', '中信出版社', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('稻草人 快乐读书吧 三年级上册推荐阅读(中小学生课外阅读指导丛书)无障碍阅读 彩插励志版 300000多名读者热评！', '叶圣陶著', '2012-06-01', '时代文艺出版社', '15.80');
insert into book (name, author, year, publisher, price) VALUES ('在你们离开以前（当当专享信纸，一本治愈两代人的生命自度书）', '毕啸南 著,博集天卷 出品', '2021-08-01', '湖南文艺出版社', '48.00');
insert into book (name, author, year, publisher, price) VALUES ('可以不睡觉，一直玩吗（送给全天下的不睡觉世界冠军们）', '小杨叔叔', '2021-04-01', '新世界出版社', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('局外人（如果你在人群中感到格格不入，一定要读《局外人》！全新精装插图珍藏版！诺奖作品，人生之书，耐人回味。）【读客经典文库】', '(法)加缪 著；读客文化 出品', '2019-03-01', '江苏凤凰文艺出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('亮丽精美触摸书系列（全4册）', 'Maurice Pledger，荣信文化/编译', '2011-09-01', '未来出版社', '275.20');
insert into book (name, author, year, publisher, price) VALUES ('大卫不可以+大卫上学去+大卫惹麻烦（大卫系列全3册）——清华附小推荐《大卫上学去》；凯迪大奖绘本《大卫不可以》！', '文/图：〔美〕大卫?香农David Shannon', '2019-10-10', '河北教育出版社', '119.40');
insert into book (name, author, year, publisher, price) VALUES ('半小时漫画科学史系列（全3册）（从地心说到相对论，半小时读懂人类如何从蒙昧走向理性）（专享知识脉络图）', '陈磊.半小时漫画团队 著；读客文化 出品', '2021-05-31', '文汇出版社', '132.00');
insert into book (name, author, year, publisher, price) VALUES ('大中华寻宝系列（1-28 上海寻宝记/北京/天津/重庆/山东/四川/湖北/浙江/甘肃/陕西/江西/江苏/云南/河南/安徽/湖南/香港/贵州/青海/澳门/广西/福建/河北/新疆/海南/黑龙江', '孙家裕', '2021-08-01', '二十一世纪出版社', '980.00');
insert into book (name, author, year, publisher, price) VALUES ('陪孩子走过小学六年（全新增订版）（新版）', '刘称莲', '2019-07-23', '北京联合出版公司', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('认知觉醒：开启自我改变的原动力', '周岭', '2020-09-01', '人民邮电出版社', '59.80');
insert into book (name, author, year, publisher, price) VALUES ('南明史（全二册）（当代历史学家/明清史专家顾诚先生扛鼎之作、荣获中国国家图书奖和北京市哲学社会科学优秀成果一等奖）', '顾诚', '2011-08-01', '光明日报出版社', '88.00');
insert into book (name, author, year, publisher, price) VALUES ('山海经 精装珍藏本 中国远古百科奇书，是地理方志亦是神话故事集 精装插图 名社新版', '富强译 注，高高国际 出品', '2016-06-30', '作家出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('月亮与六便士（精装典藏版，未删节全译+详细详注+12幅高更画作+14幅毛姆照片）', '〔英〕毛姆 著 ；苏福忠 译', '2019-06-01', '时代文艺出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('这里是中国2 百年重塑山河 入选北京市科学技术协会 “2021年优秀科普读物推荐书目”  典藏级国民地理书星球研究所著 书写近代中国创造史 中国建设之美家园之美梦想之美', '星球研究所', '2021-06-22', '中信出版社', '198.00');
insert into book (name, author, year, publisher, price) VALUES ('海蒂怀孕大百科（全新第5版，  百万育儿大V大J小D、年糕妈妈推荐！）', '（美）海蒂·麦考夫，（美）莎伦·梅泽尔 著，新经典 出品', '2019-04-01', '南海出版公司', '68.00');
insert into book (name, author, year, publisher, price) VALUES ('理想国', '柏拉图', '2012-05-01', '中国华侨出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('养育女孩（新版）', '[澳]史蒂夫·比达尔夫', '2020-03-23', '中信出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('胡萝卜的种子', '（美）露丝·克劳斯， 爱心树童书  出品', '2018-09-01', '北京联合出版有限公司', '29.80');
insert into book (name, author, year, publisher, price) VALUES ('目送：龙应台“人生三书”之三（彩插新版）', '龙应台 著，理想国 出品', '2014-01-01', '广西师范大学出版社', '43.00');
insert into book (name, author, year, publisher, price) VALUES ('小英雄雨来 童年 爱的教育 六年级上册快乐读书吧推荐阅读（中小学生课外阅读指导丛书）套装共3册', '管桦，高尔基，亚米契斯，', '2019-09-01', '南方出版社', '49.40');
insert into book (name, author, year, publisher, price) VALUES ('快乐读书吧 小鲤鱼跳龙门 一只想飞的猫 孤独的小螃蟹 小狗的小房子“歪脑袋”木头桩 全彩注音小学二年级上推荐阅读（有声）套装5册 二年级课外阅读', '金近，陈伯吹，冰波，孙幼军，严文井', '2019-06-01', '商务印书馆', '109.00');
insert into book (name, author, year, publisher, price) VALUES ('金奖图书 小学生必背古诗词75+80首涵盖小学教材要求必背古诗词129首 30万多读者好评,不同印次随机发货 团购电话：4001066666转6', '说词解字辞书研究中心', '2014-02-01', '华语教学出版社', '28.00');
insert into book (name, author, year, publisher, price) VALUES ('这就是地理（全8册）畅销书《这就是物理》《这就是化学》系列新作', '米莱童书', '2021-01-01', '北京理工大学出版社', '200.00');
insert into book (name, author, year, publisher, price) VALUES ('三十六计 彩图注音版 小学生一二三年级6-7-8-9岁课外阅读书籍世界经典儿童文学少儿名著童话故事书', '龚勋 编', '2020-03-01', '北京日报出版社（原同心出版社）', '16.80');
insert into book (name, author, year, publisher, price) VALUES ('幸福小鸡系列（6册。日本畅销婴幼图画书。萌萌的小鸡五胞胎、趣味横生的日常生活故事，和爸爸一起快乐洗澡、和妈妈一起开心逛超市、和外婆一起做团子……）', '工藤纪子', '2018-01-01', '接力出版社', '108.00');
insert into book (name, author, year, publisher, price) VALUES ('作家榜经典：老人与海（全新未删节插图精装版！海明威作品！人可以被毁灭，但不能被打败！读经典名著，认准作家榜！）', '[美] 海明威 著，作家榜经典 出品，鲁羊（诗人作家） 译，大星文化，Slava Shults 绘，', '2017-02-20', '浙江文艺出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('孩子的品格——写给父母的积极心理学', '彭凯平', '2021-07-31', '中信出版社', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('非自然死亡：我的法医笔记', '刘晓辉 著，真故图书 出品', '2020-11-30', '台海出版社', '52.00');
insert into book (name, author, year, publisher, price) VALUES ('那个不为人知的故事', 'Twentine 著,酷威文化 出品', '2020-10-01', '四川文艺出版社', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('原生家庭:如何修补自己的性格缺陷', '（美）苏珊·福沃德 著，阳光博客 出品', '2018-06-01', '北京时代华文书局', '58.00');
insert into book (name, author, year, publisher, price) VALUES ('洛克菲勒留给儿子的38封信', '（美）洛克菲勒　原著，张占磊　编译  知书达礼 出品', '2012-10-01', '中华工商联合出版社', '28.00');
insert into book (name, author, year, publisher, price) VALUES ('信谊世界精选图画书-蚯蚓的日记', '[美] 朵琳·克罗宁 著；[美] 哈利·布里斯 绘；陈宏淑 译', '2013-04-01', '明天出版社', '42.80');
insert into book (name, author, year, publisher, price) VALUES ('从你的全世界路过：修订本（张嘉佳亲笔签名版与普通版本随机发送）', '张嘉佳 著,博集天卷 出品', '2019-07-01', '湖南文艺出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('红楼梦原著版（上、下册，全两册，全本120回）（团购电话:400-1066666转6）', '曹雪芹', '2013-01-01', '人民文学出版社', '59.70');
insert into book (name, author, year, publisher, price) VALUES ('神笔马良（小学语文“快乐读书吧”二年级下阅读。生词、疑难点增加注音注释，阅读无障碍）', '洪汛涛', '2018-01-01', '浙江工商大学出版社', '21.00');
insert into book (name, author, year, publisher, price) VALUES ('和大人一起读（全4册）小学一年级上册 快乐读书吧 推荐阅读（有声朗读）小学课外阅读', '樊发稼编选，朱永新主编，', '2020-06-01', '商务印书馆', '42.80');
insert into book (name, author, year, publisher, price) VALUES ('曾国藩传（张宏杰新作）', '张宏杰', '2019-01-01', '民主与建设出版社', '68.00');
insert into book (name, author, year, publisher, price) VALUES ('吴军数学通识讲义（原来数学可以这样用！文津图书奖得主吴军全新力作，一本写给所有人的数学通识讲义）', '吴军 著; 得到图书 出品', '2021-04-15', '新星出版社', '99.00');
insert into book (name, author, year, publisher, price) VALUES ('忙忙碌碌镇（精装）', '斯凯瑞　著，斯凯瑞　绘，李晓平　译', '2014-06-01', '贵州人民出版社', '58.00');
insert into book (name, author, year, publisher, price) VALUES ('德国精选科学图画书 套装4册（北大附小推荐书单 肚子里有个火车站+牙齿大街的新鲜事+皮肤国的大麻烦+大脑里的快递站）', '〔德〕安娜·鲁斯曼', '2020-08-01', '北京科学技术出版社', '144.80');
insert into book (name, author, year, publisher, price) VALUES ('大宇宙  和爸妈游太空  给孩子的手绘天文绘本', '马劲', '2020-03-23', '北京联合出版有限公司', '79.90');
insert into book (name, author, year, publisher, price) VALUES ('我变成一只喷火龙了!——第一届丰子恺儿童图画书奖 获奖作品，儿童经典情绪管理绘本！', '文/图：赖马', '2019-11-12', '河北教育出版社', '45.80');
insert into book (name, author, year, publisher, price) VALUES ('森林100层的房子', '【日】岩井俊雄', '2021-06-01', '北京科学技术出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('写给儿童的中国地理（全14册）', '陈卫平、陈雨岚等 步印童书 出品', '2016-09-01', '新世界出版社', '392.00');
insert into book (name, author, year, publisher, price) VALUES ('中国民间故事:田螺姑娘 非洲民间故事:曼丁之狮 欧洲民间故事:聪明的牧羊人 快乐读书吧五年级上册推荐阅读(中小学生课外阅读指导丛书)套装3册 彩插无障碍阅读 智慧熊图书', '扬光编选，（意）伊塔洛 卡尔维诺等著，尚金格等编译', '2020-06-01', '商务印书馆', '57.40');
insert into book (name, author, year, publisher, price) VALUES ('神奇校车  探索人类进化（官方授权图画书完结篇精装纪念版）', '(美)乔安娜柯尔 著 ,(美)布鲁斯·迪根 图 大J 译', '2021-07-01', '贵州人民出版社', '48.00');
insert into book (name, author, year, publisher, price) VALUES ('人生没什么不可放下：弘一法师的人生智慧（弘一法师彻悟一生的人生真谛，帮你重遇未知的自己，逆袭人生！）', '宋默 著，文通天下 出品', '2014-01-01', '团结出版社', '32.80');
insert into book (name, author, year, publisher, price) VALUES ('一个陌生女人的来信（茨威格中短篇小说选，豆瓣9.4高评分译作，德文直译无删节）', '〔奥〕斯蒂芬·茨威格 著  高中甫 韩耀成 译', '2017-09-01', '时代文艺出版社', '22.00');
insert into book (name, author, year, publisher, price) VALUES ('华夏美学：与《美的历程》《美学四讲》并称李泽厚“美学三书”，深刻洞见中华传统美学，一本书读懂中国美学史', '李泽厚', '2019-07-01', '长江文艺出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('自在独行 贾平凹的独行世界（畅销300万册的国民精神读本，中国作家协会推荐精读）', '贾平凹 著 时代华语 出品', '2016-05-01', '长江文艺出版社', '39.00');
insert into book (name, author, year, publisher, price) VALUES ('孩子没关系逆商培养图画书（全5册）', '（韩）杨泰锡著', '2016-03-01', '新疆青少年出版社发行部（教辅）', '140.00');
insert into book (name, author, year, publisher, price) VALUES ('狐狸侦探系列（3册）', '[德]弗朗齐斯卡·比尔曼  程玮 译', '2021-08-03', '接力出版社', '105.00');
insert into book (name, author, year, publisher, price) VALUES ('小英雄雨来 （新版本，手绘精美插图）', '管桦；小当当童书馆出品', '2019-04-01', '辽宁少年儿童出版社', '26.80');
insert into book (name, author, year, publisher, price) VALUES ('晚安，工地上的车（小车迷床头的晚安书）', '[美]谢丽·达斯基·瑞科尔/著；[美]汤姆·利希藤黑尔徳/绘；阿甲/译', '2021-07-01', '海豚出版社', '58.00');
insert into book (name, author, year, publisher, price) VALUES ('价值：我对投资的思考 （高瓴资本创始人兼首席执行官张磊力作，团购请致电400-106-6666转6）', '张磊 著 湛庐文化 出品', '2020-09-30', '浙江教育出版社', '118.00');
insert into book (name, author, year, publisher, price) VALUES ('社会心理学（第11版）', '（美） 戴维·迈尔斯（David Myers）著，新曲线 出品，侯玉波，乐国安，张智勇 等译', '2016-01-01', '人民邮电出版社', '128.00');
insert into book (name, author, year, publisher, price) VALUES ('心的千问（庆山与读者的一千个问答。直到道理变成真正的经验。“每个问题都有共鸣，每个回答都有受益。这些问答是心的镇定剂。”）', '庆山，果麦文化 出品', '2021-06-01', '天津人民出版社', '68.00');
insert into book (name, author, year, publisher, price) VALUES ('几米：不睡觉世界冠军', '幾米 绘，（英）西恩·泰勒 著，爱心树童书 出品', '2021-04-01', '新星出版社', '59.80');
insert into book (name, author, year, publisher, price) VALUES ('故宫六百年（上下册）（去过故宫1000多次的史学大家阎崇年完整讲述故宫600年）', '阎崇年', '2020-04-30', '华文出版社', '139.00');
insert into book (name, author, year, publisher, price) VALUES ('笨狼的故事注音版（全8本）', '汤素兰', '2016-06-01', '湖南少年儿童出版社', '160.00');
insert into book (name, author, year, publisher, price) VALUES ('心流：最优体验心理学', '(美)米哈里·契克森米哈赖 著；张定绮 译', '2017-12-01', '中信出版社', '49.00');
insert into book (name, author, year, publisher, price) VALUES ('德国精选科学图画书——牙齿大街的新鲜事（北大附小推荐书单 附音频）', '安娜?鲁斯曼', '2017-07-01', '北京科学技术出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('费曼学习法（用输出倒逼输入）', '尹红心 李伟 著 时代华语 出品', '2021-03-01', '江苏凤凰文艺出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('朝花夕拾(语文教材“名著导读”经典·七年级上。大语文理念打造：思维导图+详细注释+知识拓展+彩色插图)', '鲁迅 著', '2020-04-21', '时代文艺出版社', '26.00');
insert into book (name, author, year, publisher, price) VALUES ('很美很美的猜谜书(升级版)：巴黎彩绘解谜手册！激发孩子数学兴趣入门书！172道谜题+200幅中世纪风格插画，精雕细琢的图腾，全书充满故事性与神秘感', '（法）法布里斯?马萨                希尔文?路易勒', '2021-06-17', '北方文艺出版社', '68.00');
insert into book (name, author, year, publisher, price) VALUES ('冬牧场（精装典藏版）', '李娟   著 ，新经典  出品', '2018-11-01', '新星出版社', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('云朵面包白希那经典绘本系列 云朵面包', '【韩】白希那  著 明书  译', '2016-08-01', '接力出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('富兰克林自传（《美国独立宣言》起草人的励志人生）', '[美]本杰明·富兰克林 著，潘丽先 译', '2017-12-01', '时代文艺出版社', '25.00');
insert into book (name, author, year, publisher, price) VALUES ('海底两万里（语文教材“名著导读”经典·七年级下。翻译家陈筱卿先生译本）', '[法]儒勒·凡尔纳 著 陈筱卿 译', '2017-09-01', '浙江工商大学出版社', '25.00');
insert into book (name, author, year, publisher, price) VALUES ('一千零一夜（青少版，又名《天方夜谭》。中国阿拉伯文学研究会副会长郅溥浩等阿拉伯语原版翻译）', '郅溥浩 等译', '2017-08-01', '浙江工商大学出版社', '27.00');
insert into book (name, author, year, publisher, price) VALUES ('观山海  “百鬼画师”杉泽绝美诠释山海经', '杉泽 著,博集天卷 出品', '2018-06-01', '湖南文艺出版社', '168.00');
insert into book (name, author, year, publisher, price) VALUES ('好妈妈胜过好老师（尹健莉老师从正面管教心理抚养父母的言语非暴力的父母话术来养育男孩养育女孩）', '尹建莉', '2017-08-08', '作家出版社', '49.00');
insert into book (name, author, year, publisher, price) VALUES ('影响力（经典版）（团购，请致电010-57993380）', '（美）罗伯特·B.西奥迪尼（Robert B.Cialdini）著 湛庐文化 出品', '2016-09-01', '北京联合出版公司', '54.90');
insert into book (name, author, year, publisher, price) VALUES ('希腊神话故事 快乐读书吧 四年级上册推荐阅读(中小学生课外阅读指导丛书)无障碍阅读 彩插励志版 26000多名读者热评！', '（德）施瓦布', '2018-10-01', '南方出版社', '24.80');
insert into book (name, author, year, publisher, price) VALUES ('做最勇敢的自己', '[英] 妮古拉·金尼尔 著，杨涤 译', '2019-06-01', '上海译文出版社', '58.00');
insert into book (name, author, year, publisher, price) VALUES ('温妮女巫魔法绘本中英双语平装版套装(17本/套)', '（澳）瓦莱丽·托马斯 著，（英）科奇·保罗 绘，任溶溶 译', '2018-07-01', '外语教学与研究出版社', '306.00');
insert into book (name, author, year, publisher, price) VALUES ('没头脑和不高兴（注音版）（简单的故事，不简单的道理）', '任溶溶原著 上海美术电影制片厂摄制', '2017-10-01', '南方出版社', '20.00');
insert into book (name, author, year, publisher, price) VALUES ('佐贺的超级阿嬷', '（日）岛田洋七 著，爱心树童书 出品', '2020-06-01', '南海出版公司', '39.50');
insert into book (name, author, year, publisher, price) VALUES ('少有人走的路：心智成熟的旅程（白金升级版）', '[美]M.斯科特·派克(M.Scott Peck)  ，译者：于海生  严冬冬  ，正清出品', '2020-10-20', '北京联合出版有限公司', '42.00');
insert into book (name, author, year, publisher, price) VALUES ('手绘中国历史大画卷（全8册）', '一米阳光童书馆 著', '2021-03-01', '北京联合出版有限公司', '798.00');
insert into book (name, author, year, publisher, price) VALUES ('人生的枷锁（又译《人性的枷锁》，毛姆自认的完美作品，写给在现实中迷茫的每一个人）', '[英]威廉·萨默赛特·毛姆 著，黄水乞 译', '2016-09-01', '作家出版社', '50.00');
insert into book (name, author, year, publisher, price) VALUES ('一日三秋（刘震云睽违四年新作，用幽默化解成年人的崩溃瞬间，人生中总有一日胜过三秋）', '刘震云', '2021-07-01', '花城出版社', '58.00');
insert into book (name, author, year, publisher, price) VALUES ('透过地理看历史', '李不白', '2021-01-13', '台海出版社', '48.00');
insert into book (name, author, year, publisher, price) VALUES ('画给孩子的二十四节气 : 精装彩绘本（中国第五大发明，非物质文化遗产）', '施英巍著 知书达礼 出品', '2020-04-01', '吉林美术出版社', '58.00');
insert into book (name, author, year, publisher, price) VALUES ('时代广场的蟋蟀：麦克米伦世纪大奖小说最新升级版', '[美]乔治·塞尔登', '2020-11-01', '二十一世纪出版社', '25.00');
insert into book (name, author, year, publisher, price) VALUES ('暖房子·屁屁侦探系列（套装共7册）', '【日】Troll/文、图 甜老虎 黄春琦 译', '2020-07-01', '海豚出版社', '115.00');
insert into book (name, author, year, publisher, price) VALUES ('秘密 （日本读者票选东野作品第 2名，仅次于《白夜行》）', '东野圭吾 著，新经典 出品', '2017-11-01', '南海出版公司', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('曹文轩文集典藏版（全7册）', '曹文轩   著', '2013-09-01', '天天出版社有限责任公司', '168.00');
insert into book (name, author, year, publisher, price) VALUES ('Python编程 从入门到实践 第2版', '[美]埃里克·马瑟斯（Eric Matthes）', '2021-05-01', '人民邮电出版社', '109.80');
insert into book (name, author, year, publisher, price) VALUES ('三十六计 小学生儿童文学三四五六年级7-9-10-12岁课外阅读书籍世界经典名著青少年故事书彩图全解版', '龚勋', '2016-06-01', '北京日报出版社（原同心出版社）', '19.80');
insert into book (name, author, year, publisher, price) VALUES ('下雨的书店（全4册）', '（日）日向理惠子 著，（日）吉田尚令 绘，爱心树童书 出品', '2021-08-01', '新星出版社', '133.00');
insert into book (name, author, year, publisher, price) VALUES ('希望之线（东野圭吾新代表作，高分作品TOP5！）', '（日）东野圭吾  著 ， 新经典  出品', '2021-04-01', '南海出版公司', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('培生幼儿英语大家族·典藏版：全202册（预备级70册+基础级84册+提高级48册+40张认读卡片）', '海豚传媒、培生集团出品', '2019-05-01', '长江少年儿童出版社', '888.00');
insert into book (name, author, year, publisher, price) VALUES ('关键对话：如何高效能沟通（原书第2版）（珍藏版） 团购电话:4001066666转6', '[美] 科里·帕特森、毕崇毅 译', '2017-05-05', '机械工业出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('新参者（2016版）', '（日）东野圭吾 著，新经典 出品', '2016-02-01', '南海出版公司', '39.50');
insert into book (name, author, year, publisher, price) VALUES ('刀锋（毛姆经典哲思之作，苏州大学方华文教授全新修订&amp;详细注释本）', '[英]毛姆 著,方华文 译', '2018-05-14', '时代文艺出版社', '38.00');
insert into book (name, author, year, publisher, price) VALUES ('罗生门（芥川龙之介小说集。《人间失格》作者太宰治是芥川的头号书迷）', '［日］芥川龙之介 著，高慧勤 译', '2017-12-01', '时代文艺出版社', '31.00');
insert into book (name, author, year, publisher, price) VALUES ('希腊神话故事（小学语文“快乐读书吧”·四年级上阅读。了解西方文化的基础课，也较适合中学生阅读）', '古斯塔夫·施瓦布, 译者 高中甫', '2017-03-01', '浙江工商大学出版社', '24.00');
insert into book (name, author, year, publisher, price) VALUES ('好想和你在一起（全4册，英国凯特·格林威大奖提名畅销绘本）', '[英]海伦·史蒂芬斯 著/绘；漆仰平 译', '2021-05-01', '福建少年儿童出版社', '150.00');
insert into book (name, author, year, publisher, price) VALUES ('东野圭吾：沉默的巡游 （2020年全新力作 中文简体版初次上市）', '（日）东野圭吾  著 ， 新经典  出品', '2020-03-01', '南海出版公司', '59.00');
insert into book (name, author, year, publisher, price) VALUES ('长腿叔叔（教会孩子们面对困难如何自强、面对挑战如何自信、面对帮助如何感恩。）', '（美）韦伯斯特 著  知书达礼 出品', '2019-04-01', '吉林美术出版社', '58.00');
insert into book (name, author, year, publisher, price) VALUES ('半小时漫画世界史2（ 四大文明古国组团出道，为啥只剩中国屹立不倒？其实是一本严谨的极简世界史！混子哥新作！）', '陈磊.半小时漫画团队 著；读客文化 出品', '2021-06-30', '北京日报出版社（原同心出版社）', '49.90');
insert into book (name, author, year, publisher, price) VALUES ('大中华寻宝系列 秦朝寻宝记', '京鼎动漫', '2021-01-01', '二十一世纪出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('科学家故事100个（叶永烈）', '叶永烈', '2017-01-01', '长江文艺出版社', '29.00');
insert into book (name, author, year, publisher, price) VALUES ('猜猜我是谁系列套装（全4册）', '（美）尼娜兰登　　著，张芳　译', '2014-11-01', '北京联合出版公司', '100.00');
insert into book (name, author, year, publisher, price) VALUES ('三十六个字', '阿达', '2015-11-01', '连环画出版社', '26.00');
insert into book (name, author, year, publisher, price) VALUES ('14只老鼠全集（全12册）', '（日）岩村和朗', '2018-04-01', '接力出版社', '225.60');
insert into book (name, author, year, publisher, price) VALUES ('世说新语（全2册·中华经典名著全本全注全译丛书-三全本）', '朱碧莲，沈海波　译注', '2014-09-01', '中华书局', '66.00');
insert into book (name, author, year, publisher, price) VALUES ('婴儿数学玩具书（共12册）', '【韩】金京兰  等', '2019-04-01', '接力出版社', '300.00');
insert into book (name, author, year, publisher, price) VALUES ('华夏万卷字帖5本装 正楷一本通田英章书 楷书硬笔书法学生成人钢笔字帖 大学男女生临摹描红手写体', '田英章 书', '2017-07-01', '上海交通大学出版社', '35.00');
insert into book (name, author, year, publisher, price) VALUES ('虫洞书简：给青少年的74封信', '王溢嘉', '2020-01-01', '台海出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('美学四讲：与《美的历程》《华夏美学》并称李泽厚“美学三书”，奠定李泽厚在西方哲学界的泰斗地位，一部让李泽厚与柏拉图、亚里士多德比肩的伟大著作。', '李泽厚', '2019-07-01', '长江文艺出版社', '39.00');
insert into book (name, author, year, publisher, price) VALUES ('哈利·波特与密室（《语文》教材推荐阅读书目，外国儿童文学经典，新英国版封面平装版）', '（英）J.K.罗琳', '2018-11-01', '人民文学出版社', '43.00');
insert into book (name, author, year, publisher, price) VALUES ('家人闲坐，灯火可亲 汪曾祺散文集（愿你有家可回，有人可等。三餐有味，四季有景）', '汪曾祺著，文通天下 出品', '2020-04-10', '光明日报出版社', '45.00');
insert into book (name, author, year, publisher, price) VALUES ('西游记幼儿美绘本（全10册）', '吕进 改编，吴家晔  贾雄虎 绘，海豚传媒 出品', '2018-05-01', '少年儿童出版社', '199.00');
insert into book (name, author, year, publisher, price) VALUES ('日本蜡烛图技术：古老东方投资术的现代指南（随机赠送当当专享财富笔记小册子，畅销30年的金融投资经典！《华尔街日报》《洛杉矶时报》《财富》重磅推荐！知名金融学者丁圣元翻译修订）', '[美]史蒂夫·尼森 著,丁圣元 译,博集天卷 出品', '2020-03-01', '湖南文艺出版社', '98.00');
insert into book (name, author, year, publisher, price) VALUES ('童年 快乐读书吧六年级上指定阅读 《语文》阅读丛书 人民文学出版社', '（苏）高尔基', '2018-07-01', '人民文学出版社', '30.00');
insert into book (name, author, year, publisher, price) VALUES ('一园青菜成了精（国际安徒生奖提名画家熊亮作品，中国原创绘本经典，原汁原味的中国故事）', '熊亮 著，果麦文化 出品', '2017-08-01', '天津人民出版社', '20.00');
insert into book (name, author, year, publisher, price) VALUES ('托马斯和朋友宝宝睡前故事（30册）', '（英）HIT公司 著，童趣出版有限公司 编', '2017-10-01', '人民邮电出版社', '98.00');
insert into book (name, author, year, publisher, price) VALUES ('共情的力量：情商高的人，如何抚慰受伤的灵魂', '[美]亚瑟·乔拉米卡利(Arthur Ciaramicoli) [美]凯瑟琳·柯茜(Katherine Ketcham)  著，开森心理 出品', '2019-01-01', '中国致公出版社', '49.80');
insert into book (name, author, year, publisher, price) VALUES ('0-3岁行为习惯教养绘本（全6册）', '[比]让娜·阿什比 著/绘；谢逢蓓 译；心喜阅童书出品', '2018-01-01', '长江少年儿童出版社', '100.80');
insert into book (name, author, year, publisher, price) VALUES ('复活（精装大开本，托尔斯泰三部曲之一，草婴翻译，无删节全译本）', '〔俄〕列夫·托尔斯泰 著   草婴 译', '2019-10-30', '时代文艺出版社', '73.00');
insert into book (name, author, year, publisher, price) VALUES ('动物农场（乔治·奥威尔经典的讽喻之作 ，也译“动物庄园”，后附英文版）', '〔英〕乔治·奥威尔 著，姜希颖 译', '2018-03-01', '时代文艺出版社', '24.00');
insert into book (name, author, year, publisher, price) VALUES ('中国通史（吕思勉先生写给普通读者的中国通史入门书）', '吕思勉　著', '2015-01-01', '民主与建设出版社', '39.80');
insert into book (name, author, year, publisher, price) VALUES ('塔木德', '（美）塔尔莱特·赫里姆　著，邹文豪　编译 知书达礼 出品', '2009-02-01', '中国画报出版社', '36.00');
insert into book (name, author, year, publisher, price) VALUES ('走到人生边上——自问自答（增订本）', '杨绛', '2016-07-01', '商务印书馆', '48.00');
insert into book (name, author, year, publisher, price) VALUES ('全景式图画书 开车出发系列（共7册）', '间濑直方 著，彭懿 周龙梅 译', '2017-08-01', '二十一世纪出版社', '140.00');
insert into book (name, author, year, publisher, price) VALUES ('碎嘴许美达的生活碎片（签名寄语版）（“怎么能长成旷世奇才？”——马丽、张伟丽、张含韵、苗圃、毛川、东北酱、浪胃仙、邵英)', '许美达', '2021-06-01', '中国大百科全书出版社', '58.00');
insert into book (name, author, year, publisher, price) VALUES ('薇娅推荐 小学生心理学漫画(全6册)6种心理能力，培养好性格，内心更强大。从小心理健康，成长越挫越强！(小学生漫画系列)', '小禾心理研究所 著；读客文化 出品', '2019-12-09', '江苏凤凰文艺出版社', '196.80');
insert into book (name, author, year, publisher, price) VALUES ('爱你就像爱生命（2021版）', '王小波  著 ， 新经典  出品', '2021-08-01', '北京十月文艺出版社', '49.00');
insert into book (name, author, year, publisher, price) VALUES ('一读就会用的分类成语故事（把成语用起来！随书附赠价值99元在线学习码，全10册，歪歪兔童书馆出品）', '歪歪兔童书馆', '2020-05-01', '海豚出版社', '450.00');
insert into book (name, author, year, publisher, price) VALUES ('论法的精神(上下卷)', '孟德斯鸠', '2012-05-01', '商务印书馆', '99.00');
insert into book (name, author, year, publisher, price) VALUES ('绿野仙踪（原版插图本，影响孩子成长的经典童话，儿童文学翻译家张炽恒未删节全译）', '〔美〕莱曼·弗兰克·鲍姆 著，张炽恒 译', '2016-10-12', '北京联合出版公司', '20.00');
insert into book (name, author, year, publisher, price) VALUES ('不吼不叫：如何平静地让孩子与父母合作', '[美]罗娜·雷纳 著,钟煜 译 青豆书坊 出品', '2016-03-01', '上海社会科学院出版社', '32.80');
